#ENC[AES256_GCM,data:O38pC8G6Yc1qJghZKm1KUMjFe9SPyooHnrcfcYkTkAddOJSp72/hYPmJR0csLX3XWZgJ6oUYblcZcq2g95fojnTtlG1nVV5hf49hIA==,iv:2EfPY4DG5PWgjQ1yoNN5oCAYXQ+SXTyZU2FVUfodBbs=,tag:DgOx1rSLkkKKER2j+2Ulag==,type:comment]
#
#ENC[AES256_GCM,data:tu7VqNnvAtDDoyHXoAqwgY6ga3D1I9UttpkSEBnJL1UwSvJzYiqa6ZTLp7/fS1GTSHdyh2w/ENKofITE,iv:kpNOFHDMolJxFRp1spQQyYVdcjQ/1xmDsSIhvw71qIQ=,tag:GPbWvYBv6DihrvJyNWdJzg==,type:comment]
#
#ENC[AES256_GCM,data:4K0nlkogNQ==,iv:dORmrSrJs8IoCdEe/T5/E+3iIA8ucc3HBgDUKwwuLhg=,tag:Bp9jBArCJOCTfDIVrT45eQ==,type:comment]
#ENC[AES256_GCM,data:JsfKpcxtoDvSIbF6DSmqLWBaV3k895WbOZwt+El5NA==,iv:0hNpmy69yYFK2ucCxJ6i2R8TEAoAT9CzKIhlRzegkXY=,tag:9xTUmanBUje3L3mFh8zzfg==,type:comment]
#ENC[AES256_GCM,data:ThG6Ecj4SjCEWzkb+vxUFzxXmUAnIrF8hULqh+VqO9HmD3lmHUWEYRPzpK38wLCgbsP0vBW228T4ip5SRwF8KSQM0xj/tiym1RUaE3k0qiGoNdPrderbSWDK1pkDHddBsdJ8PMrytaZFRmOt,iv:iOwnK0p7tr0+bwKZcjVOXXtbLTvO8jZWJTxU6NUVveM=,tag:pBtfqcPo4ZLk+q6YbRliqg==,type:comment]
#ENC[AES256_GCM,data:d/3ifFHumT4O4KHLpyL5nMN6EX4oC67BsgcNObCcIJGKOgiSUXO66QSfXyS4iYKZ8UEtn6NxXe3CZpQEhDkKDPFh6893unAiGsskw/kMHBuj1whnTNieveQro/YbJ8V1ZMIKIKzsrnaSCjSp+ZiNcASNuppisg==,iv:z5wtaPjJtkwBgeCXS9gsmXgpWsbWrCMCqn+eDx8C6F4=,tag:hpCBiKIogCmXic1mpuRhGA==,type:comment]
#
#ENC[AES256_GCM,data:l//L6jy0HA+URtDwK24Y4IdkNozhO63sDwA1qg==,iv:BmqLehg6bmS73s6F6dDrbtQPJT9+UtgriGm1YosnZIg=,tag:GU5to0qPWoHj3RZStUUG/A==,type:comment]
#ENC[AES256_GCM,data:IbQ6IKJlJtEjq+4NoGmwskaSa2w0WocpFj3d3xdO9lIi6QgXtgaF6wjNT6HUhTgRXBRUODu9nB/Ua3M35gZlyLUm13Xkgy6hxr+1Bz+KC7toSLY4esHaisf3uwQ=,iv:d4gu1JGm6SFffg2gxQyN5PVg79oGQ0rJ9FZ35pLXAog=,tag:kHcWRxij5Mit+x7Pv2eGlg==,type:comment]
#
#ENC[AES256_GCM,data:+iTZ9zx/7KAVGWGZlH4TkCoeydumyW67F68Z9LgruUDvtA==,iv:iSfDgLJ0JALit9hh9N/bDXvzK+y9NBxA9B4+Sy4hNIA=,tag:Zi8zSARYIVJU7B+nFovklQ==,type:comment]
#ENC[AES256_GCM,data:nhW+76EBJVvoEMVdYe58NPRKhLym/yfB8hSL+B2XWeO4n6mS5+gKxZkn6HJOXyr6jJ3J3tERid0H7xmYI5A=,iv:uXC0WM9NsNiKXQUqDd4Rl4eQZc1uxFYQ7S+qdoMxJq4=,tag:E/+5BbKmwiEi6munmazFOA==,type:comment]
apiVersion: ENC[AES256_GCM,data:O/4=,iv:hQ0uHrWMuSosxamkZmsBZ4eIZwctdtvi2TWWiefZEF8=,tag:ifu3g66c9/LSQCAD9TxB3A==,type:str]
kind: ENC[AES256_GCM,data:VnUrKs0N,iv:kmXFgflsjru0zceuhYAiqYcxCsrdImu+MDK1RKAjGHo=,tag:+tZs25WgpYaoL1fChLItAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V4OrCxq3a2gvkJhSIr+f47OFbjM=,iv:4qWuk1n2xTHWPpry3zUo6vPKncNqdz5VQjjPcMWJXqc=,tag:OAJX5QEX18nU6XsxozZ/5g==,type:str]
    namespace: ENC[AES256_GCM,data:8EXXB5hI//xDgA==,iv:dgKiEXKajbv32l6xnQHsEnMl9fXBpztAByYAjd3TINg=,tag:xuf6ee5t24Sh808tAnwDlw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:XYeeKHLQwM0=,iv:bZcfvytItiFnLyMAyee0lN10uxSv6GVKR572lfvOE9I=,tag:gqr5a7JxyUGjGJ/SiWTS1w==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:RVV1kwbRo6qRBaNSfi/B/45hdo8=,iv:t0qq2PQcMknhGDcrbjFg1aahp3D0vqzDNmWCVz/IeoA=,tag:TbYU7aTZaSEplVJksHLUUA==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:EFVP5ji0U+us9HEryLTEE0Kl5jAY72js0uQ=,iv:DQ9hEqemGZ5prBYoznr0HpWk8x5Ag2Gpl8CSooV/SU0=,tag:eZm2bz3wK8pqRTHZxPfg9A==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:wtgbZA2/GzMz,iv:qmpW/1OMjrCbIjbJ0LkgQUiXB5Gd+akWh7XLHThpQmc=,tag:+iAbz7gWmVhtNdbHLs+5kg==,type:str]
type: ENC[AES256_GCM,data:0xAJh+Rq,iv:LUuwcWuauL4CubpVB5vcyU3eNPcTeDxuQCUygD++FDE=,tag:NL2AIf2nDJuqMV/t08S0uA==,type:str]
stringData:
    JIRA_API_TOKEN: ENC[AES256_GCM,data:9tkxk7BRUYqjLu8RJAbDlX99ansAfe+S6pjyFf5ZYN9TTCrnL/TacrUr0e9zCbac65SwUC0XbONFHC99zL4LmXH8c25g8N4SBVINftTLeSIKY9/wU/vXsbZBDWnMk/lF6efaqIqUO+t26lQYIk37sBki24nZXfj+E/CUzdqoQ4dJv6ACCa4tCEtYyqfOJsLPpHHKReMEoUAtpsR3JqIG4OJ8oyY4AFPzEyOICyWpY4fMgyz/CL6Du9vmAbELO55t,iv:wB14FRg5/727tGLYsLLkIpGadUn4ZL1yGkug7TTTZRY=,tag:aaLhAlyqxzC6P2Y11dwZYg==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WmFYcnlnLy9EbkxyMGtG
            ZGZXQkY4ZkRxcTBzL2duV2hpU0NkU0Q4MzFzCktVdkcxTDkvaVFtRExCSFBmVlNI
            S3FTdlhYSFFVQitRWnlyRGtRQkJzaGMKLS0tIEFEakRVYUZPQXRRckhQUzBDQVhY
            UjFKSDI1YlcraWNaOGdJTW9RVzdNVDQKbxIsLnRHcckqfogPFsyvvLpmOH0rKPDw
            5bh4zLIDxKvtXGwzPMxj+tVETpS8I9PSlOebXFaz2OjE5vj4ENEoEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWmxPbCtINnQ0bnFKZlQr
            N2tHRDlaU2M5U1YrNnVEblMwU0NKRGl2K0d3CkJXOHFwZVpjMnhjN2ZGS2piRmVI
            MGZVcVh1VDZqTGxyZHVtZE5VcEUyOVEKLS0tIFQ3VnowcTQvaVJyMTRITW9kMSs2
            b0ZEdkVjNTB3UlRuYUM2Q054WXVrb28KmQvSI5yTjvmG1fbzHEPYmMQkf/Xy+zJJ
            9UOt6q/Ijah3HQTU7CBMyfUy/Kvm8u05/9So0e8MKnRq8rqI0fEHLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T17:54:35Z"
    mac: ENC[AES256_GCM,data:DDuiBl2M5Lbbv7aioPY8TwNHcJ3TNb9dRsS1kWHTnQde9hsY+wQ4XCvNcpFPMpdkhBx7r9BLMvqkyqi/i9EzaM8ImO8Zfz1pqPVnNG/HzYY85OF2mqWPaJtiF+KtLxrvvBE43eYOWUBdXzWzGkvh4iBJXnyUxHkvr7Vek8r6v+o=,iv:4n8mfcHF6skVBZ1Og0cebFwtcco8wzfHC4C1U8DZ9v0=,tag:tigJ52EpcIUFMQDnTnX52Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
