#ENC[AES256_GCM,data:jZVVypFgi6J/0ljCkynJ+TOZQXTCTw+FV6rvc4TBtmibXbwuvGGY1cIzAroTnKdXfyRRLxywVmIOw/FMzKvq26M=,iv:0o0YsLdYw0Tdm8NFPhyUDBT9DrHMl09NbX90/a0azHs=,tag:Y4zCFRXK+W/aetACbZUpTg==,type:comment]
#
#ENC[AES256_GCM,data:w8cw4QbbyImqL24EfnVh7pdMiiO+nGWbaeALehONHmBI9ZJXHmTIT3wc/CWMPGUpELL+Mo9YoIzeZbuILlJmAb3H+v0XzpjxoG1oe6AC,iv:Y06rzdnKqMiUtTHusjrAD5+JKorV9Ttq2RBMgSnv/UU=,tag:rjPpqsAOuAi1CCJqE+RCvg==,type:comment]
#ENC[AES256_GCM,data:qniQ79GkzK3GNFzx8X2snqV4jZ6CcCT+vnWUFERiIpqdcsRx1El/HAebmUeFzlWMqy4Siw==,iv:aE+8514ejNRQCtQIygsTI3Dn8UIOeZRWjYNhbFEfnis=,tag:0nebvzqMLOSM8T5gY3kZPQ==,type:comment]
#
#ENC[AES256_GCM,data:Izj0UbBQlLasm1VL/COx6Xgg,iv:Dz/2vlJynSAjvK5zD4fq3DDXAnLWWz2hVOOP9znPvcw=,tag:KkJ7X7IMq6i+PGXB+CHDOw==,type:comment]
#ENC[AES256_GCM,data:1jes9VIKmw3Ff1vS+j7rGp+r51EYXronuk28To1893K0LO9IY2WbcsUbdgDCHaQuil4WJWN3wAT8bkDLg0x7ERI=,iv:cwIvon6i1HYlZdNtiLmiovVL9huS3UJ6C6l4Cy0Fb34=,tag:N/RB0Xp7FXwS8uWeeag55A==,type:comment]
#ENC[AES256_GCM,data:UTXMeyQaxnHIZNxsXJkCVndDQ3DKpjg=,iv:nAsmQwvHoz9Y1r/WqGXWwRTtxcMbVlnAA0TPMqXAVA0=,tag:KxBZgoYkTFYT2Hr2TiFvRA==,type:comment]
#ENC[AES256_GCM,data:VCwnhqgKDF42q2d6RRwCtmWBgHaudaKsij5AcV4yseF35SuuEvW4lNqrUj4KrRVOmjMmq5yTVDsEJ5yhdICS6w==,iv:f9mL61WPudtXf4lVL3rcqqvi715xtGLQaNeoaDde5Kc=,tag:/+Ip9D68MzjNVZPkPawXPg==,type:comment]
#ENC[AES256_GCM,data:42+J9iR/c1CNUhP0XAMycxZ8CcJmHEGoOA/e4eQxkboPQH/+Trjeyoih0zGM1vjZwwWiv3y531FJM9uh+5TvKWuAwr0=,iv:tWEUVP+8qQpwCGfhK3yJHaWa3RO/n0zpZ+D0/tu4asY=,tag:keHjET5qdUpYpUGdlUKjZQ==,type:comment]
#
#ENC[AES256_GCM,data:5Y80YfS6Ig7ahBbUSHWOlZv4ZoKWyUWGCe+/eJGPxs/3nQtgy+QZIamlVXKHLYT92BVtjh0CtZjyFjWp9+1x,iv:SFFcMHhuhJnvYTAmb9KMsN+9D796a3/EA4kHuQ92AqI=,tag:oTf51OP0SMCXFhzpmH5boQ==,type:comment]
#ENC[AES256_GCM,data:dPP5+3Hc/ALpcGqqWtB07hmhf5NOW9hHXFIxgXXJ8Tzf/gEgw1HOgDHtYtFmF9mapwYMgzM/,iv:BwUvza4bHNr6m8SGfNOv7fPlyw4XUIf+99QuBAadsfY=,tag:O3Sk7eZqqVNkH5CafrUqSg==,type:comment]
#ENC[AES256_GCM,data:w8cw4QbbyImqL24EfnVh7pdMiiO+nGWbaeALehONHmBI9ZJXHmTIT3wc/CWMPGUpELL+Mo9YoIzeZbuILlJmAb3H+v0XzpjxoG1oe6AC,iv:Y06rzdnKqMiUtTHusjrAD5+JKorV9Ttq2RBMgSnv/UU=,tag:rjPpqsAOuAi1CCJqE+RCvg==,type:comment]
#
#ENC[AES256_GCM,data:yQO5GRxxI3xnWrcCD8SOStsH590/lFePOiTh,iv:YxY6F3SJfygAc1WYcTt2G+WLHdgtvGKpT6oACJJH1dk=,tag:Ey0Mgq/eccXRtJSupK6R3A==,type:comment]
#ENC[AES256_GCM,data:2kXO94ge7MF20BxALNVW4/NYUyf8ua8S9m1rdhQSwcDe3T4nkl9iYQjZSXDojeCxKJItNJQypRrfQmKzyx9O+gfJuDi5EHnmzASv4bXJ,iv:9Nqj373dakQuCy34Yd34xrudFVyqfAYFH1Vf8giSsi4=,tag:k2i/hsVAV4LzOV8Ve9xNfA==,type:comment]
#ENC[AES256_GCM,data:yDOrGSz7BdxsHRPNQ/XCjC+N7XtJfCnX06RHfGrdd89L2wnZZmWmP42oA2MKU1aUmT/ZmLHuuIHqPpJersfq3RRjZVxomdDUJw==,iv:7YLb1M/KiedB2pWylrb8gB6oTIb1QKomiLJuJlZGUbI=,tag:VK2vRJGeVY9D26wWQidetQ==,type:comment]
#ENC[AES256_GCM,data:O+KI8dovw7QjFS4PAysFECHc+z4OdGCjOEkaZi3FQYOHhtMmR2sd+M330F5NZPpkdHKUzZZ2ENtPLYfSkDUv5Q==,iv:nsDXZ+Dg+1QPA05P1KKW0deLlUQWU42zJ8Xwsu2HByI=,tag:T/+Q1znMfpvjhzHHcj696w==,type:comment]
#
#ENC[AES256_GCM,data:yebcr2Ab5phLP4TO7+Ks2i9JLxYQr9S062DjYiSMJkmwgsFRB77YeZqcT0lHN/srib2iMhEzm3Y=,iv:YfBAGPsqEovHKjo646gbeE6/8lzMvIqQL8tJk37tSOo=,tag:YHNcAJoxd44ZnV6GcUY3Pg==,type:comment]
#ENC[AES256_GCM,data:6jWQar+4Z4ntAH34zpGz5AdpV4zZMoJFKKfjHiuCWai3OU7qcZb5grXgSyXORlbLWsVpFnHWrG3U+AbZzrpJEaL75rE=,iv:FreHlrtNgEMA1Pab04MiMOzskCDmQCFVhIsoxQF97gA=,tag:rvTQ/OApnl5bAOdTcWMDew==,type:comment]
#ENC[AES256_GCM,data:LhFuFECZI2taz3KyOpaPssOqGjVuGGQ3ZgNkLDvlWZjhWh9ovqJGFbWYGPy91VT4e7tmXpond0GjtYoE6z9r/KsNdphKJQ==,iv:+bIUay9Bwdhd1Z3vWRQTr2tYejVC5rRPRY89d4OS7QQ=,tag:31RJIMmgf6ncFLaZGnlU2Q==,type:comment]
#ENC[AES256_GCM,data:40OrS6IVSnlaP/3JfdDMeudKyqzJloiNPjowu952CnayLiD9Tx/5Jpz5Gkikn8cXmSh+DQ==,iv:tPOnZGIzMt0IPCngtiBcPfqETm38n6phB18HOG14MJ0=,tag:GrXHHKEHXlxm4o/Rg8iGSw==,type:comment]
#
#ENC[AES256_GCM,data:XJk4xkck4VlANH4iXeQ9vQ==,iv:hU5tXtM5POigp8r9or0TyZmyFcrhk90Xk3e9ExUrIWI=,tag:oZB6IzFa3/MUs8ZvPfCS6w==,type:comment]
#ENC[AES256_GCM,data:51iUa1kFiA7YkV50NObuAMlGNB2ZEbv2JpmRWNOBi/wcZuyonL/eZV5KmdwTkL3R1Hy1qR9FIPIBgKRqWMyWo7MjzURSwqeULZz0BZockOLk9r911w==,iv:EuQmFCNUgb+LN9wll0EUdId1P4/r3oDKucWfpKg9UoA=,tag:Dy7KARkmrXR8y/twjcsYdA==,type:comment]
#ENC[AES256_GCM,data:U1UpfGrSRXK7bJSoy1bESwMwFEXw8wmdsqMsz5VHJEhWvUp2f5CSVkp/xzREdTVtidKIRB2b7bKm4XErqZb6j74WGX/fUlfnlqs2Gle5Y3KZOKTWifNQJA==,iv:80luG58W+lBsk1h/OnhHbdNREnywUbjK8CvgzWBF3mQ=,tag:3tiprOm7POnc2L1jS2J8kg==,type:comment]
#ENC[AES256_GCM,data:IU7n6W0OhkhQQw5VcusIFxhCTjsZs9URga2zWQZqshvdqWNrCyQeix9eGUw=,iv:0lxEGX3scLFqhb3ZDqcy41gDRv04yIFfQJdZwSW8DS4=,tag:jaJcT8WYQXDhPJVpOdSYNg==,type:comment]
#ENC[AES256_GCM,data:HsH5rsUf1FHqNRE2681P6t9l/lEeNGP4H+TQLUo50Iv/ljzctsk276ISXWjwgXOkmbFdwNvkphtIInpkihyeo7jPS5paTDSzzw==,iv:uUVLLhErkm4HOSYPk211CK7ulmYSl1ZYChhfp2d62Os=,tag:JT5pzrpde7CPqbYald9q/A==,type:comment]
backups:
    endpointURL: ENC[AES256_GCM,data:hvf6uldw66jr9MuKDUxgDnClkowSLVIX1yMNNnrUg780gdyrqUUVZ3MjIuJMhcTb17PAIiy+x7Ib3DtAqpDg3kc=,iv:pitcR5CHGfqFUlHWGj4M3fwuD3rVp3tw583xT1lWcuw=,tag:XQFHzuTbmJP4hWzitZXamg==,type:str]
    s3:
        bucket: ENC[AES256_GCM,data:/bg9m3t0rmEwKvg+/cIeZh7V,iv:QfPLU+dY2K6RLc8P+Cr/ekokEr1droYlsVAOi3KpdQo=,tag:7/bQ+rRWYMJ85ncBNh05fw==,type:str]
        accessKey: ENC[AES256_GCM,data:pLxXZvCLjHRvVj496WvK9k76XVks6zbzQo3MIIpKas8=,iv:DwTkFMga/2ye2yT1honjQruWpJk/19zDDxtqADMmAyg=,tag:IgpRQQQd8wUdfHW1epgINw==,type:str]
        secretKey: ENC[AES256_GCM,data:+9+IvbB+PdVmXk2+PErF1jlHt+NEdNU63/NPhk0SkEDik4v0VYP96KCtKtU5BLfDXCnNkPkLvEPKQltBFz12zA==,iv:9xUcdnOHpano6N1rRZvzSN3VKMRPEYL9oKW1wSQApPQ=,tag:Oepve745Xb+0NznQNoLSxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK0Vxb3BEdlNiczV2S3N5
            ZXJJdEhKNUpLZ1c4NWJiNVBuTjQxZjlUU2hzCnpFNklnLytteSt5RFR2amJpLzFF
            cHl4azlqd0tUNEdQak4rYlNoOTduQk0KLS0tIFpjdFFwdFg1QVh2V1AxaXNJalVa
            TFBrNlZZUEZSUjE3NFhVVUNKTm5YZjgKXOeAD4KmrllUaLgTWDX9rgRwlO4Kllnd
            qns+Q8J+2loku2NtuQrTUl7DZEdIyPHoO3+SVWIbaX/p+57nCBQKxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMVBZMnpWUUlvdjlDWnlj
            ZEg4MDg3RHlmZTYvVm1MdDNOZDZWMktnNEN3Ck9KTkk3RE1TZmRRUGxQOCs0M1o2
            blFJWk0wRVRMSEJxMTVZblVOTmc1c0EKLS0tIEdvaXNBcmNLTS9GSlVMcXdtSkxw
            OEFvdWljempub2JlSUxSeG1Tck5WalEK7LHYffxifNGHChx17Tr8QauNhc1t6EUq
            jPU8BB4sMk32uo0DePacIb9qKEWu9Fq4rQePNxQOsPxFU2qz5tYXOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
    lastmodified: "2026-08-13T09:50:36Z"
    mac: ENC[AES256_GCM,data:L7wBozdRKICWALKBTZBII7q/oFaCx1JheET4VzLc1oUIsNeOfc9naKL3yEukapqpCsokvwmdpcgNCxDWCo0iAjBqq0y/YHOapNbiDRv+bMIrhbTCYmdXrQ7drAUBdduZEQpqemmwgvnjfLhsF8QEuMEzxtO8Z7TseOB6/0qaSk4=,iv:pV7Yb0LdlKYyfZtcqqCwxiWFvKZFC28LhNqJXPCURvs=,tag:WE5GWdkHMY2BNaqaYt/Hsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
