apiVersion: ENC[AES256_GCM,data:cvc=,iv:+ESJh57MJXyXffMe5aezK6uVlEpYLIBqH8hiBokMi/k=,tag:vzehs8/2Khw7YM/OGX5Ibg==,type:str]
kind: ENC[AES256_GCM,data:k4wUcvXx,iv:k9P2MwUxoBUJuySb5Yet9GtvX1hLwnHVptJP90UFbYg=,tag:F7GJe9cjhKkM2RjzMlfNoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:O52MKufc91zD,iv:OeRwoghpHsM/49fj+TZrqQh+GHvvLM72Fe3Kl+IZih0=,tag:vbfSTmTXyZHlU3G97MyeVA==,type:str]
    namespace: ENC[AES256_GCM,data:viSaZUwY,iv:wNxkRIi1pfKc/udD3gRUz3q1EbcsHqgL4CgJVnlHvWw=,tag:5MIVN4Lmg0hRyfPv0OlB6w==,type:str]
type: ENC[AES256_GCM,data:JTi8uEAJ,iv:YM/cKkdUVnNQ6JPPqHo2VsgO9F/mxBZMI4sGjiKuOZw=,tag:pNffiZjacPDJF1+q1Sj78g==,type:str]
stringData:
    access-key: ENC[AES256_GCM,data:cAraxdCV4rQnwT8rQZpx4By2pOU=,iv:WlPKpR8vHZRE5/CxfT556NbpmNyCsL5UbrOv9eXgCug=,tag:Zd8qI3PtzmDQGHXU1CWaRQ==,type:str]
    secret-key: ENC[AES256_GCM,data:HQb950Z8PA4fEaOm54MWfNA6piwhvpEerNj4v7x/L65/yP7sNU2m,iv:fgA6uhlXyWXYpAl1ElsvlTtf8hdUsBWfR6gBGucQj7c=,tag:HjtRcB6qFLvhlD665N5cvg==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN1FMNk9ybGV4NW45dFl6
            aVBaMnF6UVhLeHNOT3BZR0QydVJMN09PdVVvCm95RGh5S1dRMHV1N1F2eWFuR2tQ
            QVFDeGtVTVJpb0dmMUlRSVBka1hlREUKLS0tIGVwdWJ4dGV3OWx6ZCtzV3RBT0ZI
            aVNCVXFlOEZkbE9uNzNMUnZOQXdBU2sKEB6dQq2ktApz4CU6BQVFWxoQtB+/+yWF
            5/xxtzNoFdXlobRCrJRB6UjCADYhNeiz+l5Cr8KCJOz5RvYr5kbvxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTnEwR1F2Vi9ZMG5tQzdG
            RmdnaHI3YkJia3FVZUgxQ1EzcSs1WERmbjNBCmVOZGg1RDJPTnUxN2FPUVJyb3JD
            UGtvZm9nVm1SbVdoTDFJZ0h5L013bWMKLS0tIGFmRm85cll4WS85eXBOekhMN3NK
            ZnRKbnptMk1MVUZSY0FTdTd0c3ZFNUkKcJP0PzNE59Oaw09D7B7svEMAXJun7E6/
            Zk2gH+KOiU0qGBHeZKgp4sVfv1Ts1ySjqMjnOdk5XGKcG7xGohWxxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUlZYYklnTmptWWF6TE1r
            S1FHL1dKNlorSkxpaXpxeE5BclVoWEwzbkQ0CndVZWZZNmlnaXJKbjJ1Y0ZkOGls
            RDBsdFdrWVhsTzd4YmtMUlJNSGdLZ28KLS0tIGkzdzNWd3JTRVBXQ2RmRy9jemV6
            aUEyd1hUQXVkbWt2NTRrMTNXeFNvTFkKLTxy8C29uG/7BmTXgAa0FlY1LlLzqvbL
            eE1qWAIUgIrhEjMKd2CclptbaRwB8NKWQp+ZimDMYTWX/X6GdT0MXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T12:27:27Z"
    mac: ENC[AES256_GCM,data:XfFVScm7lTjNRwXHdZ8FbDCOSbkRp/PPaP1FotbtO/bW540RFvVNo+JEt1i9qw8nySKK662HBraNn2lfBBHcNF+IfJKxNLqxucqTv5nU8nwQFZbQeBB92K6nLpzXejP7d9jUjGmovu2t/uWtUlGCqC9Rz0fh7lYy+SVH31AE1xs=,iv:c03iBStyOLvCRSsBPN3pNf4uQCowWlTaX8cAvEAg0z0=,tag:E0y8WUsk7bMVDIe0KqjtoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
