{ pkgs, config, lib, ... }:

let
  inherit (lib) mkIf mkEnableOption mkOption types;
  cfg = config.programs.gomuks;
in
{
  meta.maintainers = [ ];

  options.programs.gomuks = {
    enable = mkEnableOption "gomuks Matrix client";

    package = mkOption {
      type = types.package;
      default = pkgs.gomuks;
      defaultText = lib.literalExpression "pkgs.gomuks";
      description = "The gomuks package to use.";
    };

    settings = mkOption {
      type = types.anything;
      default = { };
      example = {
        web = {
          listen_address = "localhost:29325";
          origin_patterns = [ "localhost:*" ];
        };
        matrix = {
          set_presence = "online";
        };
      };
      description = ''
        Configuration written to {file}`~/.config/gomuks/config.yaml`.
        See <https://docs.mau.fi/gomuks/> for available options.
        Sensitive values (password_hash, token_key, VAPID keys) will be
        auto-generated by gomuks on first run if not provided here.
      '';
    };

    backend = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to run the gomuks backend as a launchd agent.";
      };
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile."gomuks/config.yaml" = mkIf (cfg.settings != { }) {
      text = builtins.toJSON cfg.settings;
    };

    launchd.agents.gomuks = mkIf cfg.backend.enable {
      enable = true;
      config = {
        ProgramArguments = [ "${cfg.package}/bin/gomuks" ];
        KeepAlive = true;
        RunAtLoad = true;
        StandardOutPath = "${config.home.homeDirectory}/Library/Logs/gomuks.log";
        StandardErrorPath = "${config.home.homeDirectory}/Library/Logs/gomuks.log";
      };
    };
  };
}
