apiVersion: ENC[AES256_GCM,data:VHg=,iv:07MvL6NUXo3Ekoi+Kf2YAM1o/BWZvT4RoFyYMvFa7Sg=,tag:08nigfCvTJbSzH1c0bbCuA==,type:str]
kind: ENC[AES256_GCM,data:qDIbs8EU,iv:LAPe4Tk03BtJ+BtK/V+ds7qn3iERPqg4c8C7VCj/pKw=,tag:IkVXTbmTvd1yBotlGxpAww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LXCs+uZVbsrx3mkkFSvX/0ZlNw==,iv:vQRGFdZM79+gPQslrGBb0+W/0SsEMdh4hu7lEmgWSws=,tag:+f/Rlr4NPxvJ1YII9WJZLg==,type:str]
    namespace: ENC[AES256_GCM,data:uSovicXHEg==,iv:Kxc/ccnsrAOdUIaKbPaFtpvWwznf5HgF5DOdltZdXos=,tag:17iRunQ4yC20Eq/ubpVdLw==,type:str]
type: ENC[AES256_GCM,data:lW8rPrmT,iv:zBTi0n47uCsWEDVkAgpXEPx97L5lHxGqRZzBSMi2Pec=,tag:Ne9NAZN5XpGWnFtfjBMJfA==,type:str]
stringData:
    CONDUIT_GLOBAL_MEDIA_KEY: ENC[AES256_GCM,data:Xg39Av8WHlZ18E3Xw+Uy0tL9tl4=,iv:aZkI1O48nCS6GVaTGXhhPRWw1Jee2t+XE4VCk9s5ZRI=,tag:dIwrovvzpxaAyO+VfBWtGw==,type:str]
    CONDUIT_GLOBAL_MEDIA_SECRET: ENC[AES256_GCM,data:dGgCgrgkHGPgz91gTMmlEMu65eHMrW7ipGC8B4ZvXJWNZsHBImle,iv:BU56rl/XBFmaFq8MjMjKeypbFo5MXFa5xeqPdlJzJPw=,tag:rcvhSgp8wDelIzEquqWvhQ==,type:str]
    CONDUIT_REGISTRATION_TOKEN: ENC[AES256_GCM,data:gY58NLq6nBADbR8MA2hisyJT1zhC57z4ivjH/zAQILo=,iv:LlnT0b6f/E3fyitSagcw337SveYiFHd06ZMs86ZoKbo=,tag:PJWX2rgqPWzwpW2VleZJVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSGhBd3FlOGcyQlpwYkY0
            VW9mMjhOajVmejVMZ3VQbC9mdmpZZW9hc0dVCkV0MkpLOTBRRTlIL0l6cmFmWWk3
            ckJ2WDV6OXhTOUowQUt2bkdwZ3RDTlkKLS0tIDQ1dHlZRGpBWnFxaUVMTW5KUytn
            ZEZXblhLdHNXYzVrYVpNVk8rL0JIVUkKugw7TLHxLqejklBsAnM0tdmURdQchM3J
            NCG02Yikfzvgd9Wy1u2hJ0TuDHLWerQdqVJ8ZCBfnqOE3jVpcvR2YA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUi9CUlJ0ZldoYlV5bC8w
            WVJLNVB5RjVJL1RQNTBucnpLZk00RS9uVmljCnE2cnNVbzhEbnhUNENNckpBSVlE
            dWFkWkpLOElIM0NUQ1VaUEdZUmV6eXcKLS0tIFJIdzZ6cW1vNG9JUi8xQTlMbkJW
            aWxNU1ZCcTdNTldxYzBUTGhpM0huOU0KPYa+h/WIF/r/h5uYR7XHBdbFKsDdkp99
            AEMknViAT8JK+ni+sjKbFFrcSAQ4eg2Ku0quppUc7azfcqtdE/LbeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeTdkTE03TU96c3pzRFZl
            WlU0M0NTZGsvb0J1a3R2cTdGMjlDWHg0dzBvCjIrbC9vbkRzcmRpUDY5VGNxVTJi
            eEtzWEJNSFZZVk45Z3BiNXczaC9JTE0KLS0tIDl0WkpYc0tuOTVwekxvbU8rSllE
            eGxoZnZrSlRHZlJ2dUpZUXVueEdMZ1EKXKH4UXQY/cnpYIg76IkqReMIggLjGp/3
            +IterEpsY5+IbZ9CwYXzdXPi0eAioO3dRdeH/LlaC22Jc6ixIiU8hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
    lastmodified: "2026-06-21T06:12:45Z"
    mac: ENC[AES256_GCM,data:s76H1czUqcsydBhKAtCsKlHIL/QRG8B1VrOL+ieXa61dNLtPo6C7NX0jhnwDD+CsG1/GKh9IQ6m554s+39yIXdVj7p69JCZsTf0VyB/hINNoIUsHt9iAvDeOPSJo1Sq7qSVtf32Tud0uoaLIeCt1YyyllqScotJr7gGtuPONl/Y=,iv:+T3sY5xEyRdM9psrKTkc5XdBHyiS4KatjNzaMMiBVzM=,tag:GzBqNUAm7B+reh5+fDW/lw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
