apiVersion: ENC[AES256_GCM,data:XUw=,iv:FNAQiQXttxgD8vjLzh1/S46OUQPmqXTlPyZOCmO/hvs=,tag:+XTjYSkcieR3kRGyNUJK0w==,type:str]
kind: ENC[AES256_GCM,data:nlqX0YeZ,iv:HHV6JfZ99lBnyTdTV9vGcc+kauGPyjcHK2PmFCx8NLQ=,tag:Yyl36yeM3t0+gqz5jzNCUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hZCQhJjnmj87WMgN5uDgkDLS,iv:DW3JE4csFwbEb/c9ur4rwRR/2TXkjeIK9m+ZB04eu90=,tag:jf/W0v+vQzpyaxVkRCJYAA==,type:str]
    namespace: ENC[AES256_GCM,data:bB/Z7qyp,iv:p+w7wq1zc25oZ0CIlXv/8nAQFZ9GUbof6v3gySRD2Wk=,tag:yuPFDMHl9F9JERgUVO7uUw==,type:str]
type: ENC[AES256_GCM,data:LVtgmUIe,iv:0aVHHiMd3U/xXdJxhkHkKkLASTcd3pDBoPCwcmA047g=,tag:THZoL6BDEemPHzm0/3iWWA==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:rjPlgAzm9YyJ5smR8cIiHrx4HdNSD+EWm/+JjjEE/l7/tsgtE+5TZlhJN/g4SWqcX+epYMx9JKxNoJL3b8qIb8rc1nLwTvhfWPjEr/mLI1gac2BbBf5rrW1YpmJN2152tbeYD3YJPFOeJhw3VxbjseNcR1jhFA==,iv:PPvNw7OIgETDOEFnN098shbYPUOvXSriTLhP73QKaHc=,tag:lxKGDclxoyLoIEJsjyU4nA==,type:str]
    DATABASE_DIRECT_URL: ENC[AES256_GCM,data:Y6REjHJNOh9L3nDFTMm0qKhv+fOpzKDYFkT971/hbTQsKe1NkOT1XFmP8ZqczJMBuwX8ULFBfmYdKmctR8VcvhEOiVLtmOcUCZq7KFgXTwyPqWyQlTS3cKG5VHLssl72Ak14aI1PIhPajqR/D8Lm/qGLgtMyhA==,iv:aXOvsZSloqiFfmc6XhGTCsxent4sVVtmHEPzlcmoqmM=,tag:M48CAneUtqVrFjr1/mkbmA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:+aEaZ1kH5B3DIwtRDrSNZnXiJuShqBwzzqj5z0GZhkoLovTBwIy5GArFotU=,iv:B03gUrNa84KIlqLGtQ92I9VmTVJUbT31nUKPOVDoCdE=,tag:oM5jhdoE2BtF2w3Nm6hEpg==,type:str]
    CALENDSO_ENCRYPTION_KEY: ENC[AES256_GCM,data:sd6w35Usu5O2inBXmTmX4ToUiikeg/SHFc3E+g1Vm+A=,iv:0lgcAYkAtQsEDlxfggDytTT18g0QVHgUo6ps1+tkCzc=,tag:1Lfa8bPmmzJ7kstnNfK8Wg==,type:str]
    NEXT_PUBLIC_VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:sWEJvvJ/5cnoaY1RNRsLdaMsgwxRXoFanC6UvV80GdtzNDBuvIdvWTLnmdBg0ndJVgtwxrMd3Z9cKRJE6W1ymF0xcUhfhw5dFEVW4rO+07VdCUxQZzKS,iv:tbxTtiDu01lIzLSQa8AYoOHkR0gkFRRb01kfuvYVTqY=,tag:L7YXQxKyCLdXh8jR9Ro2zw==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:JDZx78sDwACXys3AzfmBrkBzhSESoEHB0vSuVE4V9vBtGSZYXm5GyY8z1g==,iv:xt90OqxKDIl2e08WAOtMP0QK8mM6ycxvyvC+qiEgldQ=,tag:eXnJ4gDhcs4qpFT3EqUAtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOGZTQ1pYRkxNRmZndm1C
            SXZFUElmejVBVGhWNFJrSE5jSjNuN3B5ZlRBCkJuaHdueHljcGpNS3RwWDVRZ3hk
            QjA3cy9TNC9kT3F2YVpXa0hjZDMyWWMKLS0tIGVBVkVodlFpZmUvc2M0MjNXdVNx
            SUljM2xPdnI1K0NWYjhieStLZ1pYb3cKLrfsPdaMVMbGHDVXlie1LJm09Jxr/X8s
            RQrM/OafcJDHb2E+6RH9UOIQbZWNXt75pSrU3N9LUOFwshOPbw9RrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cm5ibjV0VURHanZha1hv
            d0E0bnRiTi9qUSt6MnRJWlkyWkR6T1dsQURBCjhnM2JyYU85YS9ldUhzTFZ4djd5
            dllkQ0ZpcnE3OXhVOG5yQko2dXZKWjgKLS0tIG5WaUpKVGdSUE9BbkNsc0JKUXha
            MTZaZDRpN0liQTlvTnRzcEVOVXVNSW8K8SqjRCGrLks5ACXqPHeqJamptqMBum3H
            xWrR3cGpGY9phal9t6WJ+BgJ7/CHVzjEk3OwX+ytPZd7VdYrnoETSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNWNnbDhtK1NscERaYjZG
            c2ZwWHhsdzg2UjJSTjYwbXJQeEhpQVZZSVdvCjJkQ2RidnVZVFdZY0dBZ2FwbkxH
            VU1DMC91RW9pSUFNRUpIZHh6WjJrbDAKLS0tIFZNSGF6Q21zc0x1cFltOWNIMDdM
            ZTZIYjJZMW1EeDRsZE42UmEyWjlPakUK/OUyQubQn8ICUO+VRiiX1PQCaCLE8AAS
            BQF2b2zauLoJWP441dMrPq2tU3balSK1yNwt7uyEGl4KF9vlhjT02g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
    lastmodified: "2026-09-19T02:40:51Z"
    mac: ENC[AES256_GCM,data:52EnOkiA+/5Yt5T5b2QIL621UeuDwS1SVqXZ1GrTM60/qVqT/HlXAGmI8t8LL+SQ8arVBH4erz4TFfx5Q5bZjMoYxrYdHqyTVhkaiqDRsf4VY0oo10Hc0LEN/Yhnt/nbc3+mnH6phI4WjSOif5WaHHqna+YMlnA3J+nXvSnOLdw=,iv:nbu7mbM5Z6FFNJQz9AfpbMa8cZx6N4/ZdiGV7VCT6nU=,tag:9sU80edGIxKVME6ERfHT5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
