apiVersion: ENC[AES256_GCM,data:ZQA=,iv:6+iuj8F9UHX3jRAGZDadI5Hfv97QU412wl8zNcS06NE=,tag:2AscX0q8d0EBoHh++2m5FA==,type:str]
kind: ENC[AES256_GCM,data:ogWZhWCw,iv:1dzACieYfZVFm+IFWZYGcyaiw39tDAyLzVet1e4xoVQ=,tag:jxfsjwEETQspqbc94BXnfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MlJ+R1OKbQFc1n4KamiB6Il/,iv:+rDTuTSfqAnTAV77X7HJrqEm7CtznZszw6BJUKXHV/A=,tag:k6xMTI5P/qPYMWZ7T4WTlw==,type:str]
    namespace: ENC[AES256_GCM,data:Dr/9Lbtz,iv:1m6pwwJXdhCSbmbzQgk2FC8aqG+YRaPBRJYaDPSLXLU=,tag:nBVzVOwnQZeJY7ZCEDCx3g==,type:str]
type: ENC[AES256_GCM,data:IcKfPsUQ,iv:XnImPaN37JweGwcMO6n7zQh/OrtdsVl59Es337LgxXo=,tag:67gYIo4Ol8WMYJXo7TXMaw==,type:str]
stringData:
    #ENC[AES256_GCM,data:EA7IJvoAMeBOR9yu88VFJUTQMKdHgq/9qglgQXCrif7Ovv9VbX9zikJd4tU3qBGJ5igO4EeiuD28IZTA/u65UxjcXDAQZzu4iiBTt4NW2LyFRXylcz5MV0VBsEIsaIUO4GkiUtnQSyzYpvs=,iv:d036qYZ6IbvcB13soklYhnJtA8YFiPj4MdHtvKjC6uk=,tag:d+1PF1BC+F5Aa9ni7whlgA==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:fnpDUGNjli3PFWmVt37QP4fpJRHB+7H9zWxOrpv9KZMUjSYnqG7K2TJTY0A57Trpwxew0xN7xqyQhhVABu6bNKj77dAwpiwuz+xmSXgpF2PqS8utMYOnZSMR/537B08ddLhqiHLinpRcaFVto3rjXmd/cQUc3g==,iv:ySTqnWP3wVHfCfnm3xYPuw9XX2ToD8y4xrHXPa6Fjjg=,tag:lWeJ79AlLGEFLS+PJIzJMQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:irF97+M6f+kX33bXG7A1cLaC4I4VmH4lStb05lUHbTRvRrH+4X6qkR+r1eQ=,iv:+IIyFASkDah8Ou2KDKznNI2jBUGrC+oqb/XAIr0wTBc=,tag:nYFAlj+D+rO0CMPJ1ErlVA==,type:str]
    CALENDSO_ENCRYPTION_KEY: ENC[AES256_GCM,data:AfhxA239I4OrZQjwCi9hpyNDNMkE99ZDJ0Gc0VaKNuQ=,iv:5zvozNijCaJT+/ASJNqmqQDSqmVKRmt8h5hDs95P+BA=,tag:4CvafMq4m3bzp0wT4ECCBA==,type:str]
    NEXT_PUBLIC_VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:KveK/wCe08W9G/XCrpaHFduafd7g0/Co/flU+22X7qWXqlofIA7AwGsadUxxHU04ndQi3H0XgZPnWWmKx/kwCutemOUCVrpxFLG/ZD7YmfmHTmEokL15,iv:86+if+0dZe9dSb+0+dIHJu91n3IiGFFveMhXKyXXL8g=,tag:TPo5+lU119qEieIBAziE4w==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:ugrbMjNxuvIBvM81SmHyh5P8pYQnSyZtdzn2c16Rad9RyXEqZ0skT65Ylg==,iv:7xicwzFU/81zgCE9CuBo9ynJrk+TzeNbrJkDCNqAICM=,tag:7I3N0LWmu/y9GoaoOCf/GA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRGZtWXZFYzA0eUUzSUlE
            WlZPZ0c5WUg0OUlJVTZsRC9EU0VXc0pQWUFjClJXV0xQZVRxcHM5TkFCM0NwVGRs
            ZnBscklPbFZIRFlWNk1vTm9IK1hwSjQKLS0tIGJ6dXNqLzM4UnhiWnYzTzdzQnN4
            T1BuSHMyQzZNdStEcDh1T0VMU1ZtUFEKz0jxIBPapsaezbq8/bq/K4skSQQECGXL
            UXekcBn2qJbnnNIgUZYqg37J4JmcRRic/RKqTXjRQbOGTPWSbmGTbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd0ZoY1UwZVp2NE0xOXdm
            M0tjVWgweWUydFBadUtDK0VVNHdLcHplKzJjCmEyYzM3RHdxOEdlMWdWM09QN09H
            L3phaFMvWHBkZU01cjhrK0NZVnhDb3cKLS0tIHZNWUs3NjkrOElMQjBJeXFFSGNw
            cndIc0VVempNL2VETUFSdHhYeG9hWU0K3iqxFgMG0djFjxjqvZt15rUlR8KKQ7fU
            uCYbxSliJ5k/OIYQCEBi7iAaqD3+ZlL3w+Z5g4ViS1eNMTxCIhrKCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeUlIaTBxSzRsci9XVU9W
            WnIvUlprWHZvbWJ3b3FYYTdncGlRY3loZWt3CnJRMk53dm1ucndFSGYxRWJPT21D
            UzB4VEQ4eUVDMGJ4YTUzTmR1WXllQkEKLS0tIC9FRHQ5VGJvS3hkN2FDS0piTkcv
            R3JQaStsZGdmVEJTaWpreUtxZzJUYWsKHCC8ZaatAb69pGzRQAZ12zRwPzbNUJwD
            i4JL75FYxDN3+hd9SZIGWEebnqk/VOd9i45tTDCMX9xUz12xMFNEUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
    lastmodified: "2026-09-19T01:59:57Z"
    mac: ENC[AES256_GCM,data:g0JZH4f+Zk1wL1N8q8pTQFjJaTfFaS1iFNXUnd8TCzkLBPAQ7nirG9DvZeX6+cPUCy+mrBP9kmU5DXdJCIPSVPo7t6Ge5mHA2b3TJVkxHODH/2EUnimnXzxD2noiOe/48QPp2zKXxvvT4jr2M2wbnuU7lNzRQw221RXf2teTDQM=,iv:5S1ofCV3fQ8W5FWo5XNlQhd1l0cxTe2V4HmAqyglbFA=,tag:ldjQYe3Xo48vtreVPxoR4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
