config:
    apiSecretKey: ENC[AES256_GCM,data:HGI5xnhLl8w3ZNkVZVWCVtPTSagcm9XIZqACBJxMN4WJ2tk7NAf/dRaNih0tAbe5W82Tb+OsztgL1XIia9xvu/agOi46wptE2qM1hAu/9Cr92OMup+4=,iv:kSg0QWgtYUMzRTF/+/4Db61S7n0J528myrrUKbWS5Rs=,tag:xkr7pk26wA1xSD6LpWZu6Q==,type:str]
    postgresql:
        username: ENC[AES256_GCM,data:6QW8fxK8,iv:/JAb924ZZIfSdhm2rQs/SZ3gMnJZrHGgmBUgC5A235Y=,tag:hX2VZCu/2dWfOu1MBllKbA==,type:str]
        password: ENC[AES256_GCM,data:YFt9CNORRfhBkaMjHK4r8qK0a7M4gOAa+KeaMUW6W7h7H7yTrcyDUagw+rj3WIwc,iv:M/AUcx5IftIq3Nw/EN/sZWJNebs+/HolYrxAaDCkaA8=,tag:dOvhtwowoYQtXqN6fS0olQ==,type:str]
    objectsStorage:
        s3:
            accessKeyID: ENC[AES256_GCM,data:8TUITugZZrKcCjq61MXUnnAjrlzH4Y99kCz2G8I6y1s=,iv:LlIDeed0TIE1gd8tpHyo9ZifkWzcPw0Yk4tFK7x2xoQ=,tag:/Gge4tHpjimAoYuFBX2DaQ==,type:str]
            secretAccessKey: ENC[AES256_GCM,data:zpP8LksImAssF9U2pMu3cH+0RVtrxhUFwTBTDma6vocyIVpXkasNulIwMbD8AzEVP/oTaCeQtmZA4NOATOo0eA==,iv:RL8x07PsDQNMx8Q7tQhCV+mLEYJDHfszqbbKu5MQQW0=,tag:+N/Hc3qO5wEO6yG9sPbsug==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJemRKcXpaczBGYW9CQnJu
            dVZSREc4bnplWmhpd21uSHFtMmRHSXVlVTEwCmk2cjRxWVllamNOQkRFSUJRQUQr
            aWdLMzZkYnVnYVQyaGdLZVFQbzJQTm8KLS0tIGtOQ1JhNFB3MUFUenVsNlFVSWp3
            MWNQSG04OWhMZGRhQ0UwQkg4MzlORFUKjYYjGqiEMo5EzhnIv3nJRQjdgs3Fn4gA
            77CabdtEHKnTscRsh7ZxVBbZv9G6cykTio2vPUh4coVVT87tpKINiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUU5ZSHM1TjNXVElxdW5h
            K2k4Yi9CUVZnbUtMZDhyMmRVSkg1c0tnV2hjCmsxSFg0Q2pQaFpmUHNvb09EdEFS
            Y0NkMW1aM0FUYUw3OVp1clFaQ3dqcDgKLS0tIFM5SlI4Q0pPNlRyWFI4RUNzVWJN
            bXM2OWhiRTFUY0o3eDg4UVpnOExBd3cKDSGsZqMFm3Bq1a8iQZQC0mxZfF/JKbLJ
            lfm5JD8eV53EjYSXvQ9ZrBn8HqvEX2mwh/7K0FHnFbuhSTbgQk1lmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBremhvSjdlWG4vcW51UGRz
            M2pDaXVjREdpYmRyem5HWmFkaVhJcWlzc0RBCktORm5QczJITlJvOFZVQVJYWUJJ
            bDhBTGhiQlQvdTZDWENXTWRmcHBWTDgKLS0tIE96aERSZmM2aU9hdTg4YTBTSTcr
            dmNTLzhpV25xYVNML0toeGFRUmJRTWcKK6SA5Hq197HVC/cO5OsbIg17vh6ylsA7
            xJjwpAa3LRyXmT+UB9HuXSD+e9a/OvvAM6BZAeLhRJCnKvNBJJWIvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T20:03:34Z"
    mac: ENC[AES256_GCM,data:Zm2YTSnTrknHIUvwNl92SSsE3eLCcbMiyKGhdfxL7pL3ApeKKh01aM2gJyAZPtOMuGkyMHwNWC1LYbH1Jmd4NRXLn3GUfeROZmGN5J/vYWgMxZMAal3WZ4b/2uWwhDK+Af4mQBSixqnL5XzKWnuzXsV6zCvzZwpnGk1K3U3Zcqc=,iv:ReP2N5V7/6kO3Pp0EE8K/ua+46dntjgr1sXn1DPAPd8=,tag:naZiFrQD8PKHSjGiKeYrzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
