apiVersion: ENC[AES256_GCM,data:QiU=,iv:LPU6sbLXKCQ/CcZmJwCB3K8IDfDJqzBQr94AOf+dliA=,tag:/cevHXR3qyWYD9v9lQe28g==,type:str]
kind: ENC[AES256_GCM,data:bTLA4Xid,iv:ePtl0l52x+9bqgqRfieImwZ4y5pf5PkWYIfPWKIp50Y=,tag:XOYAqx6qzpp2thTSaBdUxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n+AJ9AZMdfoYbXBIYLjB,iv:VGO109UMfmHgiW9Bkp2TZ6BFwp5lnpsV1Rq/fIG6uno=,tag:uQaT9tlWY/uHWUIs3rhhuw==,type:str]
    namespace: ENC[AES256_GCM,data:rr7GFgnhEA==,iv:ZSe1PGiWfD3aGewlbIz/wrLaaKTh8hPb5/FHqUwtUpA=,tag:XmUHTd9iqzKNXU78yuGMog==,type:str]
    labels:
        app: ENC[AES256_GCM,data:+/jp0pQjCtTP,iv:Vu9+pZO5/TK6EPaO5ckWrf7fG3PsFlImfez+cyMXLZw=,tag:9qUdNJD4EfJ+xluQI3BfIQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:dJ37Ipj4,iv:07IKzyGsqgy93f65ao+oxBvh0EL8Q6jsYKg/YodmXHg=,tag:3fLXMfHF59m6hQBTPE6qWw==,type:str]
type: ENC[AES256_GCM,data:/vYpXKH1,iv:2pFejgAq79eAgTIEzzBGHq3g7tuCzGPHzo/MnkAQ7eQ=,tag:SS32r50wcDKWFglADv/XJw==,type:str]
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:+e6oumB0MPftLwSDthOAQySK1dk=,iv:HeTfnLK78zwxvBoyRBsmvSAEi4cX9TDIWujq3zFOb5c=,tag:7K5slpT9a2J4SUBKuOe+2w==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:yfQ0gOxPp9AWvKkfMqfB0LLgEm4jcJG9mNRdo3WakbmjD0735fXx,iv:YpNozyLIwSIen3KFv+kGxTsBGFlRj7ItIOlagPU/csg=,tag:qzu0s1TsvOQQwWQ7PEUXMA==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdVRYNGI3SVhuellxN21z
            S1M4ejc2VmNqamE5SGRBNHFzaEw0c1Z1cGd3CnZXMmNXVUhvZzZuWllJeVBLdG8y
            WkYzNUExYzZzMzRaeVRja0ZZYWJYRUEKLS0tIHQ4Nisrb1RTQUY5TUxPbHNwWC9r
            RTRVcFlIM2U1Z0xUajVLckVSaXBHTGcKAulT3zZXfAUqF68l696OwkKNNbbkXMKQ
            99E7v7xNwxcCPice301WtW3oRyswbZUEo613FuJBigy3Glz3/kAruQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWUZtMmhFcjNFM3RtQ2Fa
            emhTYkVxV1liWXBBcjIvcm0zWGZzRnBHNlc0ClFYWlUrUngxRkVheExnc052OVMw
            MzhOcWlCRkduSGJHSXBWcnFKaHBmS28KLS0tIFdmSE40WVV5SjVuYk8zamdCKzg1
            dzBZTEhwUTlBZndETU5UVGlwdnJteVkKJtHrOKAPKM6Jb+vsxT0VkgIaB52UJsd7
            xoLtWYMmM/HGB5pjU99zWBx8oX89d4grqAp8QnHlGxSKm723P+Sf4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZGx4Q1dNSzJna1JCVG5V
            Q1ZVWi9vc3FqcHpUVHc2NkYxTEkyQ3ZSRUc4CkpIVno3cG5QRnFaNlEwbFo1MFFJ
            Ni9Sd1ZLbHl1eWVDdDk3azRZUzBzU28KLS0tIEZjdUEyWWd5NnFMVjArd0NJR0FM
            ckRhenBBajdpSXVaMzZmY3NRWHJBeUEKAeChgOwT/eTmxND2P0bh6a0z4uXi6zgM
            3YRQIV68fC1c3+KTHgFaanClhkQOuBixCWhlJ0w2TnctYP+FOgESDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T15:15:32Z"
    mac: ENC[AES256_GCM,data:G2j3b94yRagVwM4zLPJxj0yJhAqEWFdk8QIfREm6kvvvb/AIvxBzBCmSrLeybXL7Kp9ggHjfTlRA1ChDbajQsB7uq7iviXH5LdRa4YglVEon8g/Db9HMs0kRNITowsTMyLbiax2HyPf0yGDA1eTrDjHHjbumme4/2jiwYWKCp8I=,iv:Vfkkrm0k9E4uu5iHeWFl+t84G0GHOxTp4ex8ePHVJko=,tag:9pJ/sl4htFvIgWB5PIwGTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
