-- Nerd Font + SF Symbols icon definitions.
return {
  apple     = "",
  cpu       = "",
  memory    = "󰍛",
  disk      = "󰋊",
  wifi      = { on = "󰖩", off = "󰖪" },
  volume    = { high = "󰕾", mid = "󰖀", low = "󰕿", mute = "󰖁" },
  battery   = {
    charging = "󰂄",
    full     = "󰁹",
    high     = "󰂀",
    mid      = "󰁾",
    low      = "󰁻",
    empty    = "󰂎",
  },
  calendar  = "󰃶",
  clock     = "󰥔",
  media     = "󰎆",
  front_app = "󰀻",
  space     = "●",
  space_empty = "○",
  network   = { up = "󰁝", down = "󰁅" },

  -- App name → icon mapping (used by front_app.lua)
  apps = {
    Firefox         = "󰈹",
    Safari          = "󰀹",
    Arc             = "󰞍",
    Zen             = "󰊯",
    Kitty           = "",
    WezTerm         = "",
    Terminal        = "",
    Code            = "󰨞",
    Zed             = "󰵮",
    Slack           = "󰒱",
    Discord         = "󰙯",
    Telegram        = "",
    WhatsApp        = "󰖣",
    Signal          = "󰭻",
    Spotify         = "󰓇",
    Music           = "󰎆",
    Finder          = "󰀶",
    Preview         = "",
    Notes           = "󰎞",
    Obsidian        = "󱓧",
    Notion          = "󰈄",
    ["System Settings"] = "󰒓",
    ["Activity Monitor"] = "󰨇",
    Default         = "󰀻",
  },
}
