Secret: ENC[AES256_GCM,data:dtZI2+o3wB0uyfeuSg==,iv:YcBEz0ab4iDZpLQLZ3NT2dOh6VnAbU2afIdDQW/MrzM=,tag:L2CEPDtUzpY5WavtkBDdGg==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV09yZUpzS2VtSDVycyt0
            aXlrT3hpSm42VkhWUHh2azJZSDczVE1CdzI4CjBHTHhTb2VPajNoZTJZV1lXemZB
            S1JWcVZVeGI1eHk4QmFrWGxNUWtyU2cKLS0tIE1OV2hwaDd2Rno3Unlob05aQVdz
            Q2xKN2V5U0U1QkdqRzh2b0pnN0NvRFkKsu85q/bRBAzyWwdPttM2Ss9rsVmlyKjF
            CoPgBF5wFkMZlnQwtXElg4mzlZcTHZdPBW0+Zc7g0RVIuIm366xWFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVFh3RUFJdEhlZjJmNGRo
            UVllQjErNzdhNTNtUVkzcDJNL0NaWmhUZkc4CktJcGliL2w1akl0NUY4RFZ2elFt
            TTM3Q1IvUGlsK0QyTktNVElpeUtua2cKLS0tIEIrcnIxRWRLc1p5OVhPNXpzL2Ru
            ZlZWTXBJTTRJOEFiNVdKOWd5UFQ1dDgKKejJik38de7ciS4N75c82OAt+kUVaooI
            7JWoYmQhPtYAzPSWj6YlgGO9gtKDONfMKcr3rnujBO6P1TRwinupCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T19:30:21Z"
    mac: ENC[AES256_GCM,data:GkqhW1+tN3QkBts54KNAXueogFBKp4F0zm5U5WLuLBi380fpbQKVRKOfU9kPOgelt6eZZ+ZIdBBnfIF3SrunshTCJCzE1tigD5LQM6uIKvp/3uxDPCDflKH4J3keGySGwW+ptTXDT9zAh4CTphcaMCbLOLSwNFIqWpLkl5XcjoQ=,iv:nB3SS+A9Cnnwi55C138E3zKtiridnqPw7iHokOt09/I=,tag:UdY5qESKqTAo4fXmiyRuSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
