#ENC[AES256_GCM,data:2IfTtah9aQolzEeGQQsBndPG30KyDcsXJsY398JxrUFqUlUIsDHEj++OeDVm977G/YKnc4rRiFRPtSVdAlg9xlAYxL+eGrzYrSELWO8=,iv:JIpTzV+we6zrlvgI+ReBEtV+8beA57Sb1hU0bx3jnJk=,tag:GGLybHepB7wPvmdI8/TcSw==,type:comment]
#
#ENC[AES256_GCM,data:h1/OrY3fSyX7UUw7Q/dDnSQx2oyQdlyUTWcQBhcBxfqZFJVebJe7kV+Op75dX0V7h8YS+6aHbwUsIk5uSs4=,iv:rErbjsiS0bDVoOwgaiotQK3JTurobDlg5GvF0iXCuog=,tag:wJNiFvMvvXqPdf5vjWh9Sg==,type:comment]
#ENC[AES256_GCM,data:nPgJrx2klvtPreSX01vvPMAeq5/RZ0jKr91iQzCMQC7eA+Nv/11ZgYLcNWZebkEsmFexCmcwovIGq1ySXPg/tSvbKSf7lRa/O7BZt2vd1v5pHWtWMKl6Aw==,iv:wjW1DkaiQHqYfFFh9G9uJdU8ulhZ0ppfWW8BTWsvtXU=,tag:jw9tyLFLnSGUgLuCKZ0NqA==,type:comment]
#
#ENC[AES256_GCM,data:+TwKRxDWvIQldL2ODKm7cwQsag9CLrCUzBf29nl6bTU=,iv:L9FWYdAYhmZbVOVKh/d1eQkpDGxYBpFR5PQKu0e1LeE=,tag:WnIQ27yWLtmJC46idyOPxQ==,type:comment]
#ENC[AES256_GCM,data:yq+G0BrSR6ugcTVPv4bOxJWZ43hL/hwqCVCfP3wK9sfH+N/SoAQjKapEEGdXVfYkyLfR8lrfLmvOXVgKHpLxm5l7,iv:V2U2lw8WMX7q2n3x5bhldhfy/WkhtYXgMs1OZoDoj/s=,tag:WZ+32Q4aNlRJAM3+GF6BIA==,type:comment]
#
#ENC[AES256_GCM,data:ZVG4+5f23Gsg9jD1LDfH+3sTGehYsaOecZX+RsiszSHhMg5cynS9gfvaZgu4UW8TfC9F8KrQlBpa+wb1CNIF8NrW,iv:4WqIt3+idrwblEl+y3wfgCSzC2UgieUm4GuTq9BrK+Y=,tag:ytvd9Spfx8BBXohOe5evmQ==,type:comment]
#ENC[AES256_GCM,data:awUYPDMIZwH2igKjxytfmeHqaJXjwPCnIESHvhvwMYJ3oM7tePwQ/piCSyX8ygctDXIVRQpMRK2o4Zq9bo3b028hx3Y=,iv:lI+gmykwGc4OvBGUQE13uXAun84H6TSk7h8qiS5qQC4=,tag:EIybd67CM91Q9rnw2OZtGQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:vbg=,iv:JeJp6YBWCXR26uqGXrFkqcW6XAC9Je40Zj2OnNLxqrM=,tag:RsJE8yiu1yG5w2saqR9Hug==,type:str]
kind: ENC[AES256_GCM,data:RCi83VUF,iv:HoSt7mTxW9FCcvKi+Y3SIqrMysy084otj/qvJ+W2AbA=,tag:AdgogaUNIPAtk6RNXvp4Sw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BvfKDxs4KwfzR74fzTLE+IL2HA==,iv:014Kl9phOeY+43jirygnjOIpr+Yr1C1gwtTUQ9Jh018=,tag:5SEGE8lDy+HKH1FHjTCRIQ==,type:str]
    namespace: ENC[AES256_GCM,data:Y7jyLyTdVA==,iv:ItN8kGOjewqzV7Oicw9jaKWd1MrrDYca7UM8+XddqC4=,tag:ceIaAWBtNCK1A1T7cxu7kA==,type:str]
type: ENC[AES256_GCM,data:XUfpP+rg,iv:Ki0kogWtz1lAgKeysAqKzwNSLA87epNeI7D2mf1w9wc=,tag:v5MVEitFIEGUUSm0p7djfg==,type:str]
stringData:
    #ENC[AES256_GCM,data:+vLoXxx/uycAgZJ7nGpY2JMftiN622NaK0p7c8y/6hzcLeseIqZ+ZhOYr7e5WLgC76bZKWzrbmHt4R78qosMmZQMZNYUbGwNo0EBF/iD,iv:TQl/8+Fd+pAm/AvXEiSnaXMdwegYuLTVxCONo8yeTR4=,tag:AFYOZxYNPqL8R+jnvXruuw==,type:comment]
    LLM_PROVIDER: ""
    MODEL: ENC[AES256_GCM,data:SE9dPVZU/tuqRUWHZzLFcNqF3GI8R/7s58SqMUs=,iv:tmNXVV8sqZXxuvNChYf5N4FiQoiJjD+OP5vxdVuA7pY=,tag:pD4pZlB6iYdsXYdiVjrpzw==,type:str]
    #ENC[AES256_GCM,data:3qcX3OYG/gFEwbrXU7iG4cBBqOjQLfk6hDVFy8RAZpgO5QrZu/agodmgmDyS/XEZo4nzYIy42j7OmapcmNpSbnZoXeIaVniOug==,iv:VacnzD2ekcbj3fLk3v+xBKHyx8kHmcUx3fzjRRpkDLI=,tag:9Op7LFV7JiRR3Sg6K4H4Ow==,type:comment]
    RXRESUME_API_KEY: ""
    #ENC[AES256_GCM,data:UKqRrFOgmQoQGCjuZnz0h5BVVsXFed11/3sjt3SlG0JIHlyvJ3IFHcl0unWJKZjwPy8uzGM=,iv:eI+PctVsoYI8uucmaiVhSrxtP3sgtU1MHqGn+vc/j8A=,tag:an6da0+HcoXkvgDUp56pfw==,type:comment]
    GMAIL_OAUTH_CLIENT_ID: ""
    GMAIL_OAUTH_CLIENT_SECRET: ""
    #ENC[AES256_GCM,data:v3KGAsLXbhuAAcA1e61tgfHy9q9J6zxaN/t63E0XV+MPLfiCd0/8jUISlPq09roa,iv:hu+UqY3pjy482QDR/ij/Ya3JRUqt6DrCtbOPX4/CrZM=,tag:v8wdU0Kdg5BI+SOIzweVAA==,type:comment]
    BASIC_AUTH_USER: ""
    BASIC_AUTH_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN0VoZzNQblZOTSs1YXBG
            NEFEL2JmUm5na1FQNThjU2p1T3lZd1JUbGpNCnJBMjV3Sk9YS09zcXZHTHBTd3NW
            SUIzTlN5M3VkUlRKSUtyRXMzVmQ1cXMKLS0tIHM5WGJMM2c0Y1ExV0pJRk1yTklw
            c2h1cDFaT2xDR0F2TnJDU1RHekttRm8Kpn+SgAbJkqoHml2DMKwzoYS+7ujPjAbE
            8x67M6DlmrsVyNyWBmZktYFH9r2b/I6HX9Fc0G3stzMjvUvDzlzdAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL045Vm9YR2s5WHhTYTNq
            cGE1MkUwc2p3QWpDVmtMenoydkJqMjNFQ1h3CkhuNzNLN1ZoOThyaTNCcmpKTkgz
            NGdzVlNWWnBKQWxTekxadUM2dnY4Tm8KLS0tIFNWb29PZ3liSHR6VEhhSmZDWWpF
            dThIUFUwY0dSbFhSQkFJcjdFdHVTSXcKkd2FckSvT/6k9p/CIfvOEPreQaW/vrEM
            MWp4KqitW1Z5zejMdIYE0iYXTNAGp3vwPniXPxj3oCbqhhES+LBX0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cUhUbWI3a0dzbGRXWUpz
            ZTBwTS8xWTVpa2pWQmw4NUdoTmM3RTV4RlE4ClZiTmJpcFZhamRCQlBZZXVuQWRE
            K0lOVysrekZzdzZWbVZ3Zm1hWjNVV3cKLS0tIE9qNHNTOHVzNXFqUGxQSlB6N2lO
            dVkvOURPc2hKRC9TSGJmSU5KS2xuWGsKl8Jsy9V5D0FmVEFX1uJ/BZ1a/+gMF0JG
            dJhlk5DTGMNUIviALzsaj2ubiuUi1VTjaLZTZxhDCboGuex6Cb+DNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
    lastmodified: "2026-08-08T20:03:36Z"
    mac: ENC[AES256_GCM,data:zhajsRQTgkiOA/0LeD/1EqUeSaGIcSU+da4IOEoUCB8U38ASKK5i0K8Jj+adWkNg6kCkyudCSXT4vC83t1bgtPeRBbF8E/Au/Tnqb7tQE7v7qPE1+2fHO8tNz8X3EdaIX9KElmZkG2ZYXY+qqqSuF5JOLfVjNqeQegbJC2o43Oo=,iv:r/xarTqO9+aPXbYIZjZuqVBtS7dnxNQ7kQsTi3v3QHM=,tag:TS7CTND0NH08DxO3OVTWEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
