#ENC[AES256_GCM,data:RrevEaLd0Llry4BOq7Fme2wa7tNb9hmXGCbDCMKQTB5PpRyDNjNEltqKmZktKHl/JZ28K/iAKS9zcIb++CDYmoMGC2lH7KA=,iv:BYlHBA/J/FLBl0Ggc+6GBUvd60YhwQO3eYQXwNEQHYg=,tag:lY15WLdGcLt29Z60xvfEkA==,type:comment]
#
#ENC[AES256_GCM,data:Sd5AnJe7MVS3KTEA+fKLxz2Y+1bNjOZw5R7WTqa0XdqXvg1m/8730Sosjm2nsgBTZxim8+zCeuwgvZFjLyvPIa6k,iv:3l8pfPRNQTyjArn5nV6G1ZOlJmc3OfE+hiDnZ5iXAbc=,tag:GEeHJbcrtsc6kbfgWYBOYg==,type:comment]
#ENC[AES256_GCM,data:9Gb7b3A5KghweFr752V3JfQ51wrwE7MP41wa6i0z0iZRnmoH40cU/l0Kl9yXdrnc0X0YdRCu6v8ywiz+A1JBEmkE7Q==,iv:rMlVRf2ACEskVpd21MrrEoJ92jrB9GZwINC02fztQt4=,tag:5cdPPi4bNdRbFCrEugjVuw==,type:comment]
#
#ENC[AES256_GCM,data:5UMeUPyB0ySEdsYkbu5RrPH4OkyEba1hslc=,iv:0W4DN14hfoEEgxvBDAuAsHbvSrgm9N5pgu8BYqJwP3U=,tag:nfIxFt8TCvK6BOZ6etqe4A==,type:comment]
#ENC[AES256_GCM,data:W2kFJRk2N/iL4Ouj463zH0FhT2cfuVqln3ceGLJSJLq6731vHdwMDTzKirhhNg5N89pJbJwt6hLOWt/vggtdqg==,iv:n8Azz8naNeHr1wsphlH3jgq+8biXXJCWcLMiAm0XAcE=,tag:0uWyP7m3B7j9ozc6F6taoA==,type:comment]
grafana:
    adminPassword: ENC[AES256_GCM,data:FGSh71OoOy3Ax+TXVY6hTXEvX+rqZoWpLoq5SDn2DZkh2HaHnFoRBoUnW7zl1W34CAo3oaExCWl5ebaFfDtWtA==,iv:MXcK9LGY7NqG2AE87J82THkzwZbduZ++0w5iM6rHJMI=,tag:h8DP6D14VkvUjhUg0s0CRQ==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSnJRdjdkTlMvSmE5YWVN
            L0I3dTJUU3B3S3NnSnBKWkIxVnpva0EwckcwCnQreXhxMTJUL2ZHVjBseVNaR2VC
            UkNGVmxRVDQxc1lGc0VKQXhjYmRlaEUKLS0tIDNzb0tPMm9ad0ZqQWxVT3FHQld0
            TGdGdHJlM0NKY2U3S3diRjJzdzJkS0kKi6CwENP5PNh9aKnC/gDwRZjjnfUrPM3L
            7MOApA8zVUsK5mU6MyRnZcjIpTIh1FgW2qqxZX6AASIlt+h3g1vRdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMnhPdkw4b0ZHWXc2bWpm
            ZWxTTUFqbURCaTkvblV1S0lZcDRYVVB2WEFvCk1wVlg4VGxmbktpQjRQM2JYZmd0
            Wmd3WWV2WkdQcUMwTmNKQytJTVI0UzAKLS0tIC9JUmxEbkxSRVVjM0hyWHFlSWNZ
            WjRXRW5ZUDU1clRWU1ZtWHVjQ0dFTlUK6dpPnChTlze4kAhoX/Uf7HCeIdR/dOLh
            6gnxVQAN547Jgc/OE1uaHpJkgRZSJ3377pVIomW4yzSXKEomjN7R9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T08:05:39Z"
    mac: ENC[AES256_GCM,data:oS6EWavLL0J8g5ND1vI8iR2lHIOQrJ0BQLkNBZmpk4OruwJ3pgtKr+mj7WwXdcyRQtSUO6ObgZ5Uc1U/BXZgPUN3uckytE33Y7mNOwrXcrtQ/k5gHXq3TBwNwpUwjJLcT67a+hqdAs39vlvVcIky3CQKNAyfyf/NWiCrL7OlLp4=,iv:RYHjt49xdSu16rY34hnBgvZaaqJhjbFJdykTcsLuC7A=,tag:vqIBGxLiVYpEhfLEQP7/IA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
