apiVersion: ENC[AES256_GCM,data:HWE=,iv:ifTf6I5+uobp7z4JYz4/o0l1gYTpJ2k/sSDjY5+HWg4=,tag:xmOwqRUyYnAteD6xZ03bog==,type:str]
kind: ENC[AES256_GCM,data:7hh39VwE,iv:zLf5Cj94wT6skw3zycgSOa/gFHkHWiWG7j1ijUxVvSs=,tag:n+ghF7qzLuMJAg541qZoHw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GnNq1orZA+gSA42D+F4o8fwX/d+DOsU=,iv:uicwEcEKTs12euJrcRuKpatCSKReQbhYwHBbJiy+vfw=,tag:QNRtdY2QAy79bFZYoqbmaQ==,type:str]
    namespace: ENC[AES256_GCM,data:uZnemuI=,iv:oexbcwIsyowF5IuNqzc8vojn/HyLTi8tmW0reWaaG18=,tag:vQ2rW8VSOYBVaHFwpLUnIw==,type:str]
type: ENC[AES256_GCM,data:iAc9Udce,iv:ILArIhMmdGk6nXz4rFbMA26apyKUC0ibST5xV3lBMcQ=,tag:kffdvAqs6wbZ7aP/HjdC3w==,type:str]
stringData:
    MYSQL_USER: ENC[AES256_GCM,data:xXi1253OaM3fccU=,iv:cB2/dRClrkWC0pVeFvmAK7e+iokUSfFg563MWdF9qtY=,tag:ibL9zDojIZE6LG4fnmbs9w==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:H4dKoNUS89cATl17TAV5F3Z31rZj/Ks6syBhorgqyT0ScbqXWInDrbRxn/jAWton,iv:3aCIqvLze4E9taGY2NmaAf1W+ZZwTPpPUnzp5FLFIZw=,tag:SEnUwk2HfrIoP1kyvU1OgA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:KiVst3cD3ZTHj6Nt5pUIhdynlWOhf9vNZ3Yn6E7iRLI=,iv:vc1Fs6pPvKulQnzoAHOJycgBoToPoE8JjVnfaj8f/g4=,tag:cDq8nzgz9ceHaXS94BH+Yg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:51ZQ+VL94iUUIa6tSZn4+jhDhnAkolrzR262UVy7mmPhlih3n7PWRjF0TEAg7mwIMI5qZkbZUiV+NXmKg3iXwg==,iv:8Ir7NBwiD+YNkeH8xYNw9PEHUX+81kW9Dy94BIEa+88=,tag:su0Zi+bpdNxFYqU4KP6i5g==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb2JvZHo3Z2tkZG1OeU1k
            WlovM0dnYXcrVHI4U2VQM0IrcVBvajRwcGxZCkJtZkRoNEMvdXhOZVB1OWM5Nll4
            UVhOR1AxekRDNHRnaWJFMldJL2YvTzgKLS0tIGMyaDJPOGFOU1hNOHZzdnIvVXln
            YjhFTU9pckk4bUpGL1U5MzN2NHlkaHMKHyw0sg5dcnI7yA4kqWanh8vO87kEk4Yr
            TaBzHlzMPqaoLZVXBrwLOLxTR1/R8coPJoFTiqSQGhcKVjPUIdo0Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENEYxL3NyNDQ2eGZFcXBm
            YUxNRDJUYTd0a2l5Q3E2Q1U0Y05zUHFWN1ZzCmNRZnY2TVFxaGwwM1F4c3Y4bGZR
            RWgxWE9Za1F6d24yKzJ5ZHBOY2poTGMKLS0tIFlidGdJakg1YU1uK3NoOWZsbU8v
            ZW8wQnprWGNzdXJoU1RRVWpYdHRINUEKbWqITJ/aiClF5pQYGhYFN66+BgDQ+JIp
            fTVf7iivf96xu5ydNUmWOftUQhIzmGr0dQjnObuNEFu52G2NAzITiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUHRaVmZ2blNwV2RLMkJj
            Unh0cWFIUExhM1hKMnhnOUFXNVJNWXVNVjNBCjI4eXVTdXVIeWM0d0RVNVZzeWta
            ODEraVVuclloWit3TU5jZ1FWbGFsODAKLS0tIC9LQUdaWXNYMDgzQWJHZTQyNEIx
            MTl4NG9Xd1RONXl3eUZoV2V3b2Y0dm8Ko61MRm+8H/o3NeEjs0Qn1CtSIctPbnrs
            WQjoFAnlD9LB4KC7f3srzmZVwI2UxI88pquYXecpf7rTMX8GitGleQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T18:08:00Z"
    mac: ENC[AES256_GCM,data:sv8+YwR+Pzke1GvD3W4TPP4JP6FxRBg1tPbJBnKYdbThK+DaliuWJ2zd8UczvXulbsuL/cYZl1pP0WYvX0SzK21gzlmFabjqWmsWy6wgCIDGxSKAbeYDNcWI8HsjrgUMAGg9MBqVUj09Cgd8/S8j2nv3j7LLocPZdxVUxrXPc6g=,iv:bGO2aex1EFsoVlwG0RtvgS28GydnobVwWIMsxSzvMWk=,tag:/7ne4VnCHFmEir/ZczX6Kw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
