#ENC[AES256_GCM,data:LxuSTlp2mXOrKLx9tACF/H2X+5LvQzZNKCeVx1nr3SFd6Vg0tEtqJsuK4ktcsuD2HcThm/nwjPAfmqzSg5RSfNICxO8=,iv:9f13S2O6AWB0F+n2KvEmvkbEwDMJWeyDijrS5rkXM6o=,tag:aRKa7WeJaX/plmslA7jLdA==,type:comment]
apiVersion: ENC[AES256_GCM,data:M3Y=,iv:oC1jys2uMVgnNsnhcJxVnIYUF0Bz0xvu2Jl9iFXxy4o=,tag:zwu+KfXZbnWiDRwQQ40q4g==,type:str]
kind: ENC[AES256_GCM,data:XEM8Jx2X,iv:kpmeI1wyekdViAbtoTY3gGI6PJD2O4tqMEbl5WC3r0s=,tag:MgOvIOpjuv0dKQmpRpARsw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qfcnHoZ5dVhLn4DT4NXBcJU=,iv:LMNLfwhgVAcdLPeVj5kKz8S4koWxJxxI+NuE6yBV7Pc=,tag:r+WMi49ujUzeNVqg+lMXiw==,type:str]
    namespace: ENC[AES256_GCM,data:QsV2qR4=,iv:pKTvRn8cy6xBl1XMAhSc7uh1p3AghFVed+lZ4J6NSOQ=,tag:ucLaDiI3QXvw8n8tesyhkg==,type:str]
type: ENC[AES256_GCM,data:qK9q/D9D,iv:oNjtYdSHlAwbvsC/9R1C8TngwjW/pAquIz3eJg82+rs=,tag:yRg1USTh7TPepfgPPad5Fw==,type:str]
stringData:
    #ENC[AES256_GCM,data:YVg9oBnW7spCPElZobQ6yr1nOHa/5eKM,iv:ofjDUpHA1GG8K15sSCTb6UGsYjOjc/DPwpRgEHaMvzc=,tag:9hodUhyQDKTLL708cxOh3Q==,type:comment]
    database__connection__user: ENC[AES256_GCM,data:qDPxiL4=,iv:WBktS+xR94EEPxwDSNA2PWiO04ruDgAduINJ7BF0nKQ=,tag:frTiO5zXwXcuaz1HPC9DYg==,type:str]
    database__connection__password: ENC[AES256_GCM,data:QP2KPtpOCOi3AXNaX0LRozoz9HMQdZSzQBM9fX2NQISSmoohvVJalSsU085rb5a1,iv:PZp1x0W9BYF8I1bOgbw4G5VQ71+n+7e5+lc0f26E3x4=,tag:itYHNG/u+QyxyfLnZkxS0Q==,type:str]
    #ENC[AES256_GCM,data:HLPWeNrGuubkB2ubdVK6G6wDwnGg1TTH+ta1od/3xtrADm5+xSjycP6AZN6YWzz1ozqm3Y4kjdU=,iv:lye3ISESSjPR0vQxjaTt1CuYs5bj7RTIujl/OAwCemw=,tag:N33oFg641olwn7qSiWbGuA==,type:comment]
    storage__s3__accessKeyId: ENC[AES256_GCM,data:b2669NJ/+ksX18YHCk10uvn8/ukvPsN/HJQlMUvJHCI=,iv:1QZLdFANY4bNFP6nypUcLLSI0SGRH+cIufoPvzsnq1A=,tag:SXs0Z8fijf2mSyryXyr0qQ==,type:str]
    storage__s3__secretAccessKey: ENC[AES256_GCM,data:NHyAbNsG6ynJl2KHX9j+9Ur9of+zcDTCRhllMXgy7VQCTz66aFEN90jWaC55MHyhGG1YWxousTU8bY8pU2OAuQ==,iv:vdLA2UkbOKi6GCT+OUk8mIPiICDriZsNHCqJvhwoai8=,tag:Kq+iIL2I2YUwafUTq8EihQ==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OVh1R3hJTWFrUmlxY0tD
            dnRVWFEvMkpLb0FpN1BmSFh6S200VkZ1RlN3CklEb3JCYktpN0JXQ3VJNHEzWlgy
            YkJtRHU0U0hHOHdVZy9HQXl3SUhJMVEKLS0tIHlkN2txNFNYcCtyS0pTNm9yOVBJ
            Mm0zL0JScUljTi9URFYxVko4K0tyUkEKphk1oc8nAxuBHJ91RCEhYgnXJVpe1Ubm
            cChNowWeKe+844i90LcFhIUVOqdFo55mtK/Xcj6e6IEzi2u3ZeqT6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MVk1b1BQQUJVSmlRM0Uv
            SXBSV1RPZlhKbnJDeDdwSWVXQVdvamRMNkFNCjI1Yk1FWTl5dmI5VTdSbjZtaGFR
            OXZHL2JHSUlraURNQTdUOE53R1ZFSTQKLS0tIDM3cHduVzRHbTMxN2ZEZDVielBT
            akZzRWVZZFVLWUY3Wno5RCtyS1dxVTgKock/7ZL4yKgf56Jxz28qON/A5PgB/NwB
            RidKqzbTYn8jIFTJiuB27HwJkTqxEkufKI0bOPSQfxPyovbo1m7thQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T14:08:35Z"
    mac: ENC[AES256_GCM,data:w0mmqWZbJXxb+8Iag1AFHdV5EmROQwMk4aSGqBs8/fiWLZIkiup5kWQS6aT9S8fkWbebyoagTkLrc6NPe+lW03D3FY0X3/VJWe2j9XKz4+UxdG15Sy6DiEFDOIjEmhqwv1OZbVWMesNBjrKGZhTyfXhdbH0jVCaR56B+GgrbmFg=,iv:LOKPSrN4yRsJh2zn+0UNYo7noutuz8MdX8vZO4ktX7E=,tag:L4DYBq4msEj8cvzIqB92dA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
