#ENC[AES256_GCM,data:Kjr4y6iq9i5j5pqSgKKE0cghdC/tQTkKR9t74PjYiGSDkA8J40CKNZCGsOGOEfQdN/1PVKVWCv/QEwFfiWMk5H7LYvU=,iv:np7OW5zav+Q2ifqPr36cAVYOR7pG0hz85RAif27ff6I=,tag:YaMv6Jq3Lvx8evfU4dhJ5A==,type:comment]
apiVersion: ENC[AES256_GCM,data:+es=,iv:aa2TLVIepHvOHp9tkoBoA/qu30rOCiBRMiS5tD1tPkM=,tag:vUyRHAalmhNv3ww+BVvHZQ==,type:str]
kind: ENC[AES256_GCM,data:8lAPz06r,iv:0m2funpFYLr4CpQlns8hpiOGrASYGuiDTaPDXAaFd9E=,tag:kPqbHjVNp8679NPU0KMFfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qZLx33KyvX7naaM+htrI45w=,iv:ybuYEMYs/xHpNGhe2X87OnCQs1nXkyUkL1olbBAlZL4=,tag:/Ki6r3xXoTbfXJCXFT/r4w==,type:str]
    namespace: ENC[AES256_GCM,data:vTENA2s=,iv:a0R+jGDnMuJlo3jvZj/1EDQZqKDBxtHiqNoCETz1B4c=,tag:jGu7I/R+NFEs71oiqOcLcQ==,type:str]
type: ENC[AES256_GCM,data:KPXGQGYX,iv:EAyn5MDzxleRm2XYUwsGA7FXwpv7awad4Dy/y042JOg=,tag:Z/dSzCkkZLbNL+23M5Sjnw==,type:str]
stringData:
    #ENC[AES256_GCM,data:eCQuZeTdUsfNzAAKGPravE71WLdYrihp,iv:33N0iTMwNs5uMWRXYhs8gQa1uFQ5I+d4RVdahv1ksYw=,tag:wnvTPdLQou+w2O/0y/ojag==,type:comment]
    database__connection__user: ENC[AES256_GCM,data:CvJ0Y88=,iv:epdXFbl8+N88VGlohmVwQSYBqWPcE5Rr8K7XVSMhicQ=,tag:x2PPMirWm9EEwF7SuaKmzQ==,type:str]
    database__connection__password: ENC[AES256_GCM,data:hkhgzoWQfRVQAfv/s9csmJeK9r/3obBHsj7aRDdkyzpwNf7yeqn0MAIJsVIc4x4w,iv:5SkAJNatdnEsfY68uQu7IoCYe//cAuqkkOxq7MT7q6o=,tag:WlX7/HgPSxZ5JG6JzqKDqQ==,type:str]
    #ENC[AES256_GCM,data:jlrymC0t4a/Ivx9xtZwG08QdfBhKH4NA1vKuLOUgU8DvlQxjDLmlKSVWRXJQSalq6pMe,iv:QUEwjjdkQh/3Lxqmhm+jcVzRQCky3JWr35IcmXEY83o=,tag:mUUD7WdWPfrCXUgwf3bPgw==,type:comment]
    storage__objectStore__accessKey: ENC[AES256_GCM,data:ujYCv3z6QcYCyriqQkGLPwe5VzgaqpwF+Bgv9PnKVDg=,iv:L6B+5NCz+lFhyZ4L/HWFV5lIzbcmdC27dKCGOOIc2eA=,tag:lV/Dd862CdTIRADbVyAAkg==,type:str]
    storage__objectStore__secretKey: ENC[AES256_GCM,data:BwLuAzV8LqpaA3QvpFNZE7ML9Kj6v7hFURSzTwJkJzjknbsrw68u1eWnvX/2Gh7RvL5Dz84WDxLtU9mg4EEA9A==,iv:wkqP8HhTwMWd3giTey74cz27POnFLC+jinegen/yik0=,tag:PhQV5lL6/tZ22kG9LDpFxA==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdkRFZlJ1NkN0UVhDMWVk
            cnoyQUk4eDBPdGJScExYS3F6eVRlVC9KTVc4CkxPekoyZHZYQlI2VGtiQXRMcWd6
            ZlpYU1RnbGVXNi9NbWFLZTBCRlI1Q28KLS0tIHFlTXQ5T3psQlRRY3ZrWnlucFlT
            RnU5V0RqM3hPN08yYjcrRktxQTl2SVEKl7QfJH2Po7xcGho43im+Jym5xpYa939V
            3HD3aWHpMl+XK/60VTlb8TVcv7B88/fatJwaE6vVeSdvUZuRzDS66w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUjVpRGMrZDJZdnJROWdp
            eXRnMFFPTm9QSC8rbnBXUDQ3UmpkZS90UkNBCmVwTjhUempVbExweVRqbXY5dGtH
            a3c1UHdoVGhadDZoekJSc2VvN09McHcKLS0tIHVrRkpMekU2SWgvaXpGRkZWMWo4
            L3dnYWQ4d3hJSks5bTg0bmVrRW11VjAKTA75QViClbbpoPyb4sEv6yTNQU2xHt7n
            h5xyXK7HDfBJQoHzGcOXtqgfqe2UKaSUk1u/Gk1PpEyyu+gw7K6k/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T04:00:11Z"
    mac: ENC[AES256_GCM,data:MFfUSwYbqNqUT8SxPA2pJs4NSbY/adHC6bJAirxG2sM+M9iBZRTEYFt6dMeSWZbIlgsc5qQZ69D0BYIre0Q4o/tKeBkNDFclpMMQ88PXeqfaTH+etr9dxkH81hKcL1LFfq1DeBhPkIEJ2/Ia2maqYOg2d7CU7h6PA8szCOUmAQY=,iv:75j2zaqx1IuEltZkg4G/7HH6ZzwiksWD2oBAvvnVc+Y=,tag:P32RXbFpHZnLUqo5FoiawQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
