#ENC[AES256_GCM,data:9bCpCJQhtHvxelFukY/GYQu3YUsRVVR8gaOSTiQrP5CRRzk6f47blJVTiEngjyT6wH/06TQMBx78Nq8VRKiHRRKVerdMeY2c,iv:YTYdVdPqrif9LL/a34/CWzypeEcuWVLFVAvbTTVgUfA=,tag:NNkuvCiHVhKydphRlIfxtw==,type:comment]
#
#ENC[AES256_GCM,data:e1zx/eA5lkF9D20qUrDVZhKAZqskGiGEWd+zWUyrAQ==,iv:pKR3GZIyZSp15qBYnM8EidAATcsK5yjfa6+f7aGMAyg=,tag:B1VMHOS/xyDMj+V8EvZsng==,type:comment]
#ENC[AES256_GCM,data:JHKccA1KJ+MW3VlmwMZ51vih4Wqfq2OV9+Z58/no7F6FoTAnCbgUS3xjHSn2A//V21sW2zv21HE6OQ==,iv:XKL+RA8IDMLGJ1TLXSeDQhvd+l0LYjjnsYbGaWkhP+w=,tag:vtJl7cqXUHgM7Jiz2J/dSw==,type:comment]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRmZ2ekd5RzhxVWJTYnJy
            bnltcDMrTER0WllLeUVpSnFrdEYvL3UrOUZJClg0OXBlcG9GSlNFZnVVTWN3UVF3
            T1VPYS9KdHk4RGwxd0JPVHN0NFBVWjgKLS0tIFY5VjVrVUFHMnR0TDN6djUxeGho
            QVZlRWZGakIyNndWZEhGZGVZUUptUDAKDzvOuQqrJOBzOtQkbeiktze+UcJDziTG
            325rVvzyTciDX8mM2tdnxfEUbADaIMeojv6edfTsNfFU56gA+SfU9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQnlSWk52YTNjdWcvM2c0
            MmVjYTQrNmhYOG5pakNHTjZmR1hESDMrMlJ3CnRFTzc5UkIrSyt5aFRaUnNmbEsw
            Y0dmZHFBeFo4eWcrSjVDU1BDM1N6azQKLS0tIDlCeGdBaG8vaHE2VjUzdFN0M2hZ
            Q29lbTVNMjRWenFCckpRSDRYQ1U1Qm8KnGZLINRS3TU+Rmt27gYs6s4+vdQi3AzO
            ANPWBLXuXT7eMvugj6IeoTEegGaXN5L/wBvPJzVH9V5zj8wkKeGGpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T19:10:29Z"
    mac: ENC[AES256_GCM,data:E78KNIUW/oQ7usJkUAkYz5owSYV3U/+AXA9mR3gLGtrOLqA06GHJqZo6PYbEobjgUaG7a4u55f7Bq3xDBanmEU2Sj9o43qVdYV88DdmKJ518wosfT8PnAhWVeTEVRxRIpqL8N54iiuarXohQPqWA4EPv8v73Z1Tdk+q8IXUwxhk=,iv:+PO82mFvBgrzd9JWoBcE+R9Fy4Z9BRmso4sPDAfDLAU=,tag:9o0O996mvAWZue1fSe3Ufw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
