# aggregator-credentials-secret.enc.yaml — sops-encrypted Secret for the Aggregator.
#
# To edit: just k8s::edit-secret clusters/glug-infra/changala/aggregator-credentials-secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: changala-aggregator-credentials
    namespace: changala
    labels:
        app.kubernetes.io/name: changala-aggregator
        app.kubernetes.io/component: credentials
        app.kubernetes.io/part-of: changala
        app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    ATRG_APP__SECRET_KEY: ENC[AES256_GCM,data:zGTvIwK6Yvo5ZYjnR671X1H24Iyu9d7JUs3IwdTj2XL6CNvGfIxyINFNG2Jax5rD7lF0SdtbCZUSuGp3cDufKA==,iv:RcWMjYZrtgYbp6L5eeSZdTri6RXqC8dByVPuMfqQ4lg=,tag:75oyJ6JQltFxXaaa96AThw==,type:str]
    ATRG_DATABASE__URL: ENC[AES256_GCM,data:N4W5I/GPwjqlAiq5PS8lAa0BnjtmI2PYzzi3rAv1d/PSQY/uGUmvE03nLZXY3O+ndErN2hX1YTiLqNYn0A2s5Z/G/Rk6c0w81OeLDDG24s2c3rjcWxddhgByI/UvL8n8e23e5/Dw2d+Ux9rq,iv:N6MXc0DkPau2fC63wKgdVCi8YS5ba+zR9a8alopadnk=,tag:C7EgOwVLNr8U/yS7zvV88Q==,type:str]
    CHANGALA_DATABASE_URL: ENC[AES256_GCM,data:7Kz6eKfUO32/qG6ViFMUAvOQNNJgwaFfMO4t+h1JrPr+SXYb6hx6FbaynmB7cOR3o/8u/x+aw3/yRx5vWe82yzDayRGOWAD1szsYiVseoyHPfM2gH6nGgIBkCz5xLrjpWU1Ms6IsEv+5P2Na,iv:N7msAp9Q/jCXRynzHgO3M6o+gaf4frq5elQszNzmoLI=,tag:bW09gZ3vpiii8Emn4Otsuw==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUFZXdFNHL3VDNnpROUJC
            QjJNWEc3ek9oQWVTTEtvVmhGa1VOL3VqZEZRCkduQ0xSSk1YeUlmYUs5bi8vNENN
            YXNRaDdFV3BSUTZvclRMMkJCbitBUjAKLS0tIE5QU1FPTUtsbFAwMlIxcXdaQnVD
            WG1FaXN3ZGVPS2lMeHVmSTRQeXpqcHMKn2W4P221NkEODcwiPqFuX/7L40F795zK
            0npwy4W6KEaO0wbdqXcNqWfX+sFdqMcWKY3s2mIvOOlyS7MjdpzahQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbngwQTdMYU5seWtsQWo4
            Qi9yaDk4cU93cEtSY2xPbHZ0M1ZkTHltTmlZCmkweHduVzRnKzZTRVdhSU5KUm1M
            eGVSazJ4VUxZUFhQT1QxY25scENPVjQKLS0tIG1wc25zRVpPZDhwODYzMWlPVDlG
            Nk9JRmRKSzAzQkNMOXRIUkZ5UjRET2sKdX6rair9IkH8PqEq+KOoyv6OZAhYWsA3
            JI46KnQBvsMpYTaLa66e7n1Qyn+3ETAcYuErhduJ7Eal5yahKuFxTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:00:38Z"
    mac: ENC[AES256_GCM,data:DvKnYa6KOxQok8O1NRQw31tIVXS/Qcfn0W7nUSY6z7koOGpRIfajM+6smkQ1ly/uihh9yeh2ByAfQ0L4i5EcDS4nCTM9UtB62J4Rj7AYBIqTGW6PBaNj9mo0uvOyzfiYNG+qoJsPJAYY1n5NCl8q98TQj9DqH3WOM+XRGe7sl8A=,iv:vpm5jlQXvLoimVoGtbwybW5RUSesnT2VVM5QHejaBA8=,tag:NJ74qkL98oQmrp9+LArqSw==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
