# ring-credentials-secret.enc.yaml — sops-encrypted Secret for the Ring.
#
# To edit: just k8s::edit-secret clusters/glug-infra/changala/ring-credentials-secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: changala-ring-credentials
    namespace: changala
    labels:
        app.kubernetes.io/name: changala-ring
        app.kubernetes.io/component: credentials
        app.kubernetes.io/part-of: changala
        app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    ATRG_APP__SECRET_KEY: ENC[AES256_GCM,data:YmLYYJmyeL15R17KHCpb++zVVyPeqWexr3gcqpc6O9xZpUzpBFeeyCQ/VfXl+FicNVJ3lRa699IPjBJoMDna5Q==,iv:KbJgmVJ0Td5vo79vwcqy1N7DpLLRtDE4N1zC7m+A6HE=,tag:ou22ESowDi6rqHSGAtelyg==,type:str]
    ATRG_DATABASE__URL: ENC[AES256_GCM,data:4Z8cB9p9igkkP7n8kCQAWN4wg9n9tlDt1f0buqR+l+QnrQ5KkNVsERkE1zgQuOVWaURXfx9g1rUDTpO63ZedGtqZjBNfPc6Q0wLm1odPhVHbf3mFVoDHnqZ5eGWueUeEknQp7yd+,iv:2Cy0tysyMEE+mWb/Mwj6hnI3bUdiK7lMyFsMjz692gE=,tag:sWIu5qzryyklHbuL7OZTLQ==,type:str]
    CHANGALA_DATABASE_URL: ENC[AES256_GCM,data:0Jx3mMEbNmT8xwFuaolv/jK2m8iMd6W5Gpvbghdj05ns0rn2Wr7RNJakGcYHtFrtm7XGvuen7CpmzGHnBgPumdhIy/ca3OpB2Id0zmxAEaZUP1+99Oy/nUZidtsuNYBNmU2yMsQU,iv:A+0Pjb+EHJB/HUfDEoJmwUntWBPe7yZ/cyXQwVNni1U=,tag:Di2tVIzknqX7A33eWVc6nw==,type:str]
    CHANGALA_S3_ACCESS_KEY: ENC[AES256_GCM,data:PjBYpkb2zU21KmFX905cEAp4TYw=,iv:WXFpvuQC6JH/cf7p3BuoXgARiCe97IGKTWSEK3Q21LU=,tag:jjeXILIIy57aU0SMOusWgA==,type:str]
    CHANGALA_S3_SECRET_KEY: ENC[AES256_GCM,data:EXMvziNqsgrrQFskEvaDsPWpjonpF9k1yeuhUcwLaNN55EaQjGhXXQ==,iv:ayIB3L/ubEZZ7SHFesxfBhU5KiFsO42rGhuJDWzud+Y=,tag:NhfPLqsRh7rdMN/JTGJUJw==,type:str]
    CHANGALA_ADMIN_SECRET: ENC[AES256_GCM,data:kYwfSDkUP0VYZg8052e086f2jPATy90BLUYMOXFM2lUwd5Bx/euvZSK0kVFftOUGSVKFJ3F/IOw2WDVrZj/yhg==,iv:wMeL503cwlOmeIfKp09M9KGPnwZFOzbXqAs7lNgSF3w=,tag:j0Fwand5bik8DMOeYoe9HQ==,type:str]
    CHANGALA_BOOTSTRAP_API_KEY: ENC[AES256_GCM,data:QhN6iWD0DdAggVQAjbnqbN3cg6PZ1526tdQPyzxBZeqcOFdwVhkA2I7g0+c1bc74YGslBrDG6iW8NCxnZFy8Xab9ozk=,iv:z5MtRuVKjgfSYUjLUJE0hS9NQfyXZ311DwmdNBDieFE=,tag:aN4S2CIBvxGGVzHfR7M5fA==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUjE2VVpyZnBxYnNUd0pn
            MzVER0h0REx1VjZsL2lYOGZjQTRjaXZCS2hrCnNpMjIvcVFxTDZPbGJWVExCNWdL
            K2hlVDh2RmIyeEZGUnluT2RHTUJUVW8KLS0tIGVMVlFyZXZaTy9WVmE1bDZpVWRH
            RHBrRTZlZDBPb3hmdnJOTlZVZlVqeWsKTIhmOwASR4los9qBMDBylwetqXPW7rc1
            IDY9dQhnrkZpKSRCQTvbxXzZfrhmHDnyjNSI15rttfDNRALGgaq5qQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN0VwQWhYR2tHWjZ0b1dE
            ZmVpNVRKQkxVbnFDNW1ydEpuLzV1N1laYkFRCklvY3M2R3R3MDBERUlpZDNMR3A0
            Tjg0ZmppcnVtL21VbEovblVlNDBnak0KLS0tIDVqa0ZFTUdDMWtTRFdENXhMY2Rm
            Q3gwaXhWOUxKaXluSkw0dkZrQWlIWnMKimJS/B6RW/mOBtaEdDOiCSxfTspsdgPK
            uREsjlIi6VLQshxv3Ji5Re4FKoklbEeAq3n1uCvWcEnvrJOivOpnGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T15:22:02Z"
    mac: ENC[AES256_GCM,data:gx6MLUK6X35kx+5YhXYpGogbtnSxKSOswzxC8AMuX4F/AqetoICsOjol8BPDDujQqkvTCBsYgd/YVB/l/EEViDQOdJmbyTnbG/MtWAsawQF8pweLTfQKCVWIpIbX/w4T0/uINmvakvdNp+n3EMaQwNguJBmo9KD6mgb4oEsKqzk=,iv:/w7BVfHps8QuNPRPARzYlaUUjgcMwPLkwvhXdoD+I1I=,tag:+c/xNX8S//jM/lmk+o0X4w==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
