#ENC[AES256_GCM,data:BGvJIH+Eo4Ip7Gri3SAqi0B4eRhX0vB8yk4QuHPgQI5m1fXHmantrT7jFeng21stN6KnqPXz0P5cPx4JYFdYlk8XIbFAkFhBWZ0=,iv:K6m6qywcDZIsFCgq98zUPL6wsjcYwPejeqjs5TehRVw=,tag:RzYbJu15lrhp4Y1TwMyotg==,type:comment]
#
#ENC[AES256_GCM,data:20q9nuR7v00Icy/CtAa5M2tmQD6KzMkxOR4z/cdkw86MJSc1qGqjqM+kXZCvYIm2vhrmhda1ZY1X1n0mGEw/apfRvpAIC2Z2JjTtiA==,iv:2QyFAuBVzENWVY+pdHmGCsi8ju0MDyxneYUpIwYnhTQ=,tag:768Hw7q0Snhg3l00GHGBMw==,type:comment]
#ENC[AES256_GCM,data:/JHegPEHhG4xfBP68WHc/VJnGo/UMRKpSRODQNN4xFDXPj/CCgCl+WKQtFTAPKzScM8KricfRuq6UaaI3Q7+28V1SlujWA==,iv:top2hfyVgBW7cvjY5bTKIl1EDHLXD3IGgWvS12cyJe0=,tag:bEGBLs36422eypTfM7U2lw==,type:comment]
#
#ENC[AES256_GCM,data:d2b4YHT1+bsYObxNP84=,iv:y3oDWLacc4IlYfuVC2QAYn6ob3euQ5zfvnaabGK1HpM=,tag:F7k33y3xUi8HDgLm+4X5pg==,type:comment]
#ENC[AES256_GCM,data:v7is1auHWle4HFAJjLGfyYvFzkBelagV8PSU5jJRBfNkZnwrewEnIQ3Qaw4KlLlRo875n9RoimE=,iv:BWkxypOrWPMNm9U0m/sLjqcflpPFapyyesC3T9XoXMA=,tag:K7TUl932nttR0ck+w2yoRw==,type:comment]
backup:
    storages:
        s3-backup:
            s3:
                bucket: ENC[AES256_GCM,data:Xzl+PBFLAYciomSBf+BAl9Pk,iv:hXWUnlt3gHTBDbFqFIyyucTJiIibzij6EI4l6Ne7mz4=,tag:UCZN0dzx9YFLSSItoOMD7w==,type:str]
                endpointUrl: ENC[AES256_GCM,data:vM89UZ8QDyOOMcxJneB95djRaSet+HVUdH4OmFufbHveUqrIQdOwT/aHpC/nkP0aFAPzvwR/1CALsbrw532oAMU=,iv:P/jyY0ACKuMVEApEYJTkuAYS9zfakMa1QWxGZqJO0LM=,tag:5VkA05iDQsmiRQQ/IoNlcA==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWFk3c0ZKMEtpYlBpbWhi
            b2hoUWNZaytFeis3dzhDK0lNNXJrM3VmWm04CmpRMmpsT1FmVDlrUlljUTdiRDcx
            SkZwZUpXcVdGZHM5eG11N3FROHNxRlkKLS0tIFh0dGxDWlBBdEZHbUxlZVdqajhk
            TEJnNWE1UjlDZnRvZXNETFNxT2hUNmsKH62eOpM/P0J28wTZSgWrqlqtaw2wlKbX
            ZOH9oPDSwQibOL5JOpPBMYwx3PoL5QH6qOSabmbq/XHm4+bvhA0ZKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQUxIelkyNjlVb251bjgz
            T3hjVHIvVEZ6aCtMalp2VTlpLzloSzJrSkhnCkF3enkwS210bUpHQ0QxKzludUQ5
            NEVPWDBnZ25GWFllVE00M1MyVVZqalEKLS0tIDJ1NkpmUGtBSEUxQ0VNRzNPOTg5
            TitRclRxSWhIRGhRSjRYT1B0VTF1QTQK1evXj2CWi/N6/TkMqJ3Jd9Hc/ZTMwvxB
            MGJo5Vq/87siVybV9s4gan/Ieh9WnG+QUwBxyj+xF6uefANH7vFbCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNnNkeGFXaWdjMWY4QUha
            cW1Hb3RkL1krcVVqR0g2MTNyay8xSExuQWxnCnRzdVF5cU1pT3dlc0hPSmtnS3JV
            Tzhhc0pCNDh1alRLeUpPdDQ4Vy9IVVkKLS0tIEl6ck4zZEh3eEJZOUFBLzdPSnhj
            SmxqbFZuaDBXSHIxbEduc1YyNGlKdjAK203zk1qV85Dn1TtVHZYzKTQem4egXMZ9
            a1GsZhJFvC7boMpkym1ZhG9hgdgUC13a7tNUbtCwII3bJry9FsHk7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T16:51:59Z"
    mac: ENC[AES256_GCM,data:60+8YUzz/8ZTq1LHqWj0Kpo7Q+fDvq8H6O7scbIiys8DHlRHylLdyjb4LXwzhbFX5Hp6Om39/WUAoKL0jzVojblv/v+mQVx4QAYYkzryNfmzsDaTFNnelRB4eizsI0tNJwx0bgMa8SkgCjvJ+bxl+LqlumIwqYS311rqHRjXgCU=,iv:qIOOuUnrB7ZS9RLAUOrBtvB+Cl4ThTR7h9xFawxNrRs=,tag:ZKX0SfSG9dBwCPX5lmkIiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
