apiVersion: ENC[AES256_GCM,data:PwU=,iv:yN/RORSZaWygWK6vFjXryIB9uPbfTiSrRML37hnIofQ=,tag:V4yIfJVjn53vhLAyEg/jyw==,type:str]
kind: ENC[AES256_GCM,data:KYo6lMsI,iv:HGskrzYYnT5I+jNkIShf/9OqevegfPoffbmC6TbtJ2Y=,tag:naJBCK0HPPSOTPuyWo7u2g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:a929T7LjH/nWNQ5HQ1/Fifs=,iv:TSzhWWlqXPnHk8X7TLrDXrNDezBgCa0LKxPgFMrJwy4=,tag:Pn/LPJJ26u6wo1g6iC0UxQ==,type:str]
    namespace: ENC[AES256_GCM,data:AS3qctQ=,iv:9awnP345vW+9rpkMtHLAyNEKISchQxTd9hs+yWBX5vY=,tag:EVRefVDUqDEB8gn1fDYZ5A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:2yXsqto=,iv:YKaIc7HSEXaNM3nVYIbza+QVBpHCWFs/wciRca/PIHs=,tag:L97JePKamwwbz7BYShw3rw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:zgtnIG0=,iv:5JTenOA6++IpXVVdx2ERQF1ueUAj17W5GgVERvP3BTY=,tag:1sppZEETzkmJscnb1d87SQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:ycFgBJVahqrn,iv:ovQ7Z23KJ54hFECcguL8P40uvDE4NsNR2Euso7RmVVk=,tag:UozbIJzr4cTB2LqhMSnkIw==,type:str]
type: ENC[AES256_GCM,data:gTAlncnK,iv:DusvCtIjAwpWdWk+FHLEiYnpF6ItqXwXDqxV3hDk2l8=,tag:ymagcpn7fbASwn4ntNTH0Q==,type:str]
stringData:
    ATTIC_DB_PASSWORD: ENC[AES256_GCM,data:1lzwPaOPX1NX4ZjcdI6cU0iMaqDwHFlT1Foh00ht/eehDPwbWi/2CZnuNg7Dm8Kx,iv:9BvQ30i4gjM0PfePK8dTl6I/Zp2QDQVleZC5z5zhXhQ=,tag:wTDQRIlUQATrnj0ZuuKpUA==,type:str]
    ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: ENC[AES256_GCM,data:YkFOARO83bouVXcayCneZjt8o7koR9xzqeZfK1VhI3zmKtXux17tAeiff/mfOeyyCoHa3fWSPV2T480vc6PG3iRq/F4RYJGd35mQ6FH5V2WckFRu0zqngA==,iv:iPPGDHQw9LDxH0xO6cQkgSt98we1LQXQXVpOCwsHEsI=,tag:RY/n13HcDx2tXvVJhdPhKQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aFpjbnhZfd3YjklT759SOjEXgz91trLHYFCkYQ8OfQ==,iv:7L050v1atgoK/xcEJAnN+7ZtaF+BmGy/xMXrB+TMV2M=,tag:MEo+jYHIVWckFVSSIWA3Gw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:19zFT1xLewSQT9G5dOuWI7MzQ0o8t7iJuw/CHtEAjeMD8pWFosNR6VtSxfmTz+Pkp/uwJAuDVvDaeecFHegHaw==,iv:ga2rJlD989Zjw5zwE18oftY12qXgp2dIfWfXn6j/9Zc=,tag:cXelXnTEEFV70c790/ovoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK05mMDF5ZmJKUmxPSXhz
            K3hKazM0ZVRZTEdMY3U3SHVmVjQ5VEdRb0g4CkR6VTVZamQ1Szh0MnN0U3RsczdP
            Mk1TNVlMa2cyVVdwVHRQb0xBdnJHT28KLS0tIDBTeFRFOXZaVW15OStLa2RxSFNK
            cFovUCtMbGlUZmxpUDhwa2pKRmVmN1kKdWwnKEEdRixMimMSEqRUKLg5gjPHzOx7
            /z2UvdjSc4KNkz+YnuIuLV2UVuYesdyNeGv7gB/1gIgikykDdetjIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySjNEQU1XYVdoeWY0U09T
            bzhVTHBvenBYRExTQ1dWeXJDNUUrYUN0NTNVClpsZERZWGNBWUVNaFFYczJvd1pS
            QitlV255Q2k3VGNER1ljai9DZllrdDgKLS0tIENDS2Zzb295SW56ZEhNb251RlFP
            aGRqc0MxeGtneVpUbTh6eEZKQldHencKsTcq5YMhBE7YA6Ck2zfL5nS1SbEgNw72
            eurtnFn/DkbY4gSSp9Q/ctItGQKzpCCGKOas3NP5PdJ6A1Rwtc/+uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLam45KzQ3WkthZ1Jza0E0
            ejlYTWdZM1pHZTZYWnMwUXpGcUF5N1lTeTNzCmRLTmowUzhRdkZPQkZWSGdxaUU0
            KytKOXYxNDJ6YjVtaTM4S256bnlsZ2cKLS0tIEtQNEpQaGtqNjAwRE1acG40aVJ0
            MkdhaG00NjJBcHI3NlprUGFYdGdsTHcKpzYs7/Hxj1l/Bpw2S22C6k1DqXGUidOE
            fcLXw4kGpnJv46U5gLEqQ5cziWk3H5HCTXi6BcHbjIOMz0ba6W/5Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
    lastmodified: "2026-06-13T19:43:21Z"
    mac: ENC[AES256_GCM,data:59SMRlAYbTuz/HvAYFUTL2pu6bpU/th6HJ0Jo+iZqooYRyCKd7M+XFOlBznNKs5vxrU5On50MKuOdy9+tNA5EVzBU8nQQn5ShefpztDBvFPphseQKNyz7FULppvVs2gg89eXSWxUBDjB9tBkkoWzdW5VEiWwn0/wACVgMiG2ep0=,iv:PWGR4VaqXQTXr9Hp2UZqmOpjNPBOUSvlOkxzF1otd8A=,tag:+OYtMtF3/PWHLEXNcl5yTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
