apiVersion: ENC[AES256_GCM,data:b+s=,iv:Y1/HA/iijNYcGyP+6V6bMzdFFTp9EhEJuZuOv2ztZ6s=,tag:XnW774y8hXzb9BAfA9oPkA==,type:str]
kind: ENC[AES256_GCM,data:kf17z2S1,iv:bY2HqQfCw2x8L7FDwUAjm4SUIlYxJQsff7wulBz126k=,tag:aAWCfLn1RIe+3W+prShr8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AcXJ3kBiD8ecDIGAMTETlpk=,iv:pIxh6qLzLwsGmpyq6kzk3R59qBF4+UVs6RYWWy13+fU=,tag:TQfsFAy3bPlf2FFFTm6IxA==,type:str]
    namespace: ENC[AES256_GCM,data://Ym/rc=,iv:GujTkrV+6Kxq8C3PczlKluvjdncBhfqjnjQ263dnMS8=,tag:NmLE9HuSyC3pWhy2c/3Jrg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:I8et9ZU=,iv:LecVG+XZ2+tk7xhGiP+RJ+twOdvSsbcMQSF2XoX3VZc=,tag:W7mu0J34SJk+qNpXFAETbg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:6xVxhs0=,iv:36K9HqrMqXngQLdvex1pzWSnPy0+pSVB+P8oJYGfdFw=,tag:RJpPL3D1MgiFpjzs5gVzZQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:BZG/cqNlj8FN,iv:EPofSQEcdWi9PdcPkTVZWhvoJK+fg/f/Lcg635QZeWg=,tag:Igys8Y/8+bgU5359RsrcTA==,type:str]
type: ENC[AES256_GCM,data:8iAhDORD,iv:1gIYNsjydSzrZ0BBXnUtjNN1oN8nu035NpfS7OKWq2U=,tag:sjzliDm1v1jJl1TLdCB1jw==,type:str]
stringData:
    ATTIC_DB_PASSWORD: ENC[AES256_GCM,data:AlE4m5yTGzLVcvRxQ3Hd1EZh4GdEThhXya+pAm09muI=,iv:G/zL36C9+TwQTifcHpb5k8sCCQQL5CFGLYcwWaTZ5a8=,tag:535o0Vroz7NG7frhnzCM9A==,type:str]
    ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: ENC[AES256_GCM,data:BVkm/OFJkL6rB+aGEPoAUzURJr7vmke1VjWsDCXuUccAQ10yC6ywsGuEVMtZ6dGEcr2dRy/8CMc0GCNNbRfSHodssyGFjjVMCvummUhotT9ZamZ2TajaOQ==,iv:/m46t6H8kyIdq2Y7CTwxV/Zky8xOaUzNHPGWO8LY5pk=,tag:YTkClG9v3F0rok+CVfVhLw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:c2eEgY+8UQ9r2zUW6yW4Mmyziog=,iv:z9hct2xGLGLyJVYSJ1vciRx9XTFQd8hyDOfdg8n5ipg=,tag:9fSrrMvK0ji2Xev7kUCA+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QuCgXXRK1oGuQsHFutMXvzJObw90/Qwc7sDcjgz7lvxaa2c1naw/,iv:8MSD4IOuhOEhPOgXJ9xdudETqTqPhAac4n5LNoOJCW4=,tag:Rtrri/YpwwumgtNXNwRc0w==,type:str]
sops:
    age:
        - recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY3ZNdVEreXFwUUk2ejhG
            RUdGeXFITVlqZ3FxV0hndUZIU2ZQVkpveVVBCk8xZDVuSGxML2lQVy9ad2RYbGdD
            NElSZitPTDRhSW5VNnhTS2Q3ajVBb2cKLS0tIHpoczhkYjd1WjFxaGdwS0RUR1B5
            Vm9Wa25aeXBjTFBtWDVvcDJxb1V3ajQKZhReVLHkVXjitYIIrBAEhqAx/wQ7RnrJ
            O06Cy4JjfzWn5JxLS85tk00QuYcDETKfCCuZjxkVulHU/sGl95xwHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN1BFc0RLUTUwNGpHbk5Z
            TXNjQWVYWGhGcytXSGNLMk1CWVo5czZsWGcwCkVHdzZ5L3UzYXhHZmppb21yVlFr
            ak1PekVIQ0RPTVlpOVhuSXlOa3U3R1kKLS0tIHdvMzNLZEQ4VHhHNG9vQ0JzcHJy
            SnBySEF5ZnFYSWRDWWtBTElBbU5KWEEKnfpCOTLXbH7F6ItW35RhrqhKuyqYd/CA
            J8rT69ci0Tb8yVjxeznCTMZt2psZmTR8J8m6e9vowdTc4SF3Uzn4dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYVNPL3dya25mbVBRMGgv
            dmp3U3FJd1IrNnFxcVlCUVNRQm42RW84V2xVClMxZDVtVFBpVGgwSm0zc3BodVJ2
            T2VFUExsOVF5YnIwNTVQa1ZWYzhOSEEKLS0tIGoxYmJvbW5KTzREYUFac1BTb1h4
            eUtTU0xOL0JvRVdZRGZQaHBTU3l2czQKcqLQf6v5vJbat+tMcv3mam8/QMucEQAE
            ihsQ4o6yfgedPUitp0jbfowO0xMIfJ/+N+2OXW2CNTtjfhK9re3XWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T08:32:50Z"
    mac: ENC[AES256_GCM,data:w3cf9LYsPSmFSfi1bILCybx3VR3rzPPpSi25hRXG4qA8NGxee8hhfQ92Nk0qHb/bo2ACiJdEYOH6ECJsAuAAHz+SO4SnsxWg0aDEmILgOtE8AazYI2v8PdiqgAv2X6ZftRl8NpVxPrl63unDO0BoplEJY6raoSDQ9LTR7bD98VU=,iv:7fQFpzGXTqXYKvUA5Nz7MqsLS92E2gIA6px36TzqaFw=,tag:4UjFJ10HtMwCx0saBMzkzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
