apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - credentials-secret.enc.yaml
  - db-init-job.yaml
  - deployment.yaml
  - tailscale-service.yaml
