---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mobileapps

labels:
  - pairs:
      app.kubernetes.io/part-of: mediawiki
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - ingress-traefik.yaml
