#ENC[AES256_GCM,data:LYyQ5pi/xHmTTB/K7U1kEvUI116QsnkLB8pMfI5zkCNksTELrkJSQay0tkx/tqot/Kt5q3wxr0zucnrlXVTBSGQMjdyyy4vi,iv:efx7ICjjTIE0azqHiVxMt+gTkZlfJ0Wjxvk87szcx+k=,tag:q7d21FqXo6knWFve1jwJXg==,type:comment]
apiVersion: ENC[AES256_GCM,data:0g0=,iv:CoREsx4HwuTeD8WytFzVyzqA0EiZyO2HLUBzcG1oJnU=,tag:vPAfsOtSrZhWNk+Znj202Q==,type:str]
kind: ENC[AES256_GCM,data:26NiGdpn,iv:YuOm0viPcPUAXiOOz9/oxnwhfJsk4bhNrOqCirV/u+E=,tag:CJ+NRHeogaw6xhPaNPhcMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:U5QmHM08WQGzp1Vizi5ZrYGv5T/I,iv:QDV3EkV2bdtP5VUoIa8+HouxKavREqWrqm4hU0Yst0s=,tag:YAAc5m8ykld5YBcpYqNI/A==,type:str]
    namespace: ENC[AES256_GCM,data:C4Z2UbnY+3je,iv:/0QLsztmdJzB/OyuGrRFsVV4zdX9qq8raq9eG0K4zoQ=,tag:gi9Zlxn3Y4zv/qTnyAZs9w==,type:str]
type: ENC[AES256_GCM,data:Nk5HLLR3,iv:dFGbC24wt35xsosGOrUXYqMa5IIYanNhNCLyJf+sjTQ=,tag:VfXBjwr2Ql/cH13vFbJI5Q==,type:str]
stringData:
    MW_DB_PASSWORD: ENC[AES256_GCM,data:ESwCKbDdL4F8oLptB4V2AckwCk8I7w0INMFBLMoo0NVSM4pw0q0WYKGU0WZbDa99,iv://0EtXQuNvtdHOfKGAW36lLmIvipAatedWMUw7Tu9Cw=,tag:HQwVjDMmzZbPDoq9HqRP2g==,type:str]
    MW_SECRET_KEY: ENC[AES256_GCM,data:03yWjrrAYmsJsC6iVSxGEhIUOax8t3Hp8s0fQwB/PIfr7yvdTTeMbO9KgzKK02VND5W8zGeW99s5ZuTJklUwNA==,iv:SWUrh/XUzcRi3BvALE9XtBj9h2c7lSNiZEQXqgzuOgA=,tag:PTW5DIzQEZc2S534MHWpjQ==,type:str]
    MW_UPGRADE_KEY: ENC[AES256_GCM,data:k62H8/dtSSe8PSH4T33Erw==,iv:X50DiJg+o9Foz6pPza328GAhZSKYb3AZBNQt+k13zVk=,tag:sgPYkCg3gtIt3nxG28kHVA==,type:str]
    MW_S3_ACCESS_KEY: ENC[AES256_GCM,data:+1iovhMKRseK+IbKj34FCKr6iB0=,iv:yc8An9KifXhwZQPPnrBxzeKhcMFizuOxvJ3rc+bXV5Y=,tag:LN9YTqhg8iLhlSoSLitBDw==,type:str]
    MW_S3_SECRET_KEY: ENC[AES256_GCM,data:9u6Si+br0hNDvu9UHzzETQB+2JF4potmZxeD183k0bJ9nPehodET,iv:muiuDuNeOnA/NH38VlYuRyj0dU2ArbkSt7RDbP3c8GA=,tag:dEC2Dst4HMVR0XBWYTPOAA==,type:str]
    MW_SMTP_PASSWORD: ENC[AES256_GCM,data:Kr8PraFSjTtIQM/fFrwxZv5ASw==,iv:chxrEnharqTA+1c0sALJht1A9avd4hhdPEIrYREf8wo=,tag:DIMi097scEFz1p3xat4d+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVHZUN1g4SHFBaEs0QUhk
            UENkVHN4TzIyNVdIYXBEeW5uSTExdjFGeXcwCndsQ0VoM0I2N2xYVjdlcU92Z0Z6
            TjRJRDB4dVNwblo4eGM0YjU4ajRUNlEKLS0tIDBHK1FIT01XdjR0dEMyaEpNY3o1
            NHAvSG1WVHdBUHU5NEZPRG9BMWpTZE0KPX9TcTLCsY+LEjjSGB06T3iobw4ssYKA
            yGCnyrzp0JDqtvaNnpcgvk68c81wEsguOEgCoFOzneAWKCOv6kosVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJalF4bDB2Zm1VSk50N1l1
            eEpGN3E4WWhXanRSZlhXUzU1cDNrblFmdFFZCnV5VGRrdGxPU3VTazFnOUV1dkdu
            Q3FHd2Jyd2JpMWZWckxXVGZ5VG1MR1EKLS0tIG8vMUpneG1WR3FGaEk0WTE0N0RX
            YkZObnFRYkNoVkxleHBKMFNHVm16K1UKnUR26ZsiSB4cXeqHCZexiYfNT308KvkT
            xNefIrhbWA0Br14uryUIuyiEzFZpaaLPoT6v+UTU671u1J7q+Jgamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
    lastmodified: "2026-08-29T04:17:30Z"
    mac: ENC[AES256_GCM,data:OEIEjqH6UJdT6/QheIq+HAl+kRP8Z3kKYFj3gJz+v0COZPMCMs8LvyUjENHwy/gJKPRiMTLrjpX51c4Fu1x8v8Q4HUV5jhdj8H/Yozsda1/swUJd+c/3Ywt1zOQnJs6mc26zxOxuLcl52tWOhkdJwmMg6GmNdHmAviAsD72sVIE=,iv:/mM/0Yqe56Orl7Hz7oIv6h3tH3l1mVwIFbOhOzZwgsY=,tag:RR9DlAEUiN9h3CJ1mdjhxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
