---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediawiki

labels:
  - pairs:
      app.kubernetes.io/part-of: mediawiki
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - localsettings-configmap.yaml
  - phpfpm-configmap.yaml
  - maintenance-jobs-configmap.yaml
  - cronjobs.yaml
  - tailscale-service.yaml
  - ingress-traefik.yaml
  - opensearch.yaml
  - redis.yaml
