---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: mediawiki
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mediawiki-ingress
  namespace: mediawiki
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mediawiki
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 80
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mediawiki-egress
  namespace: mediawiki
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mediawiki
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - ports:
        - port: 3306
          protocol: TCP
    - ports:
        - port: 9000
          protocol: TCP
    - ports:
        - port: 443
          protocol: TCP
    - ports:
        - port: 80
          protocol: TCP
