#ENC[AES256_GCM,data:CmdFccU0XWXMTpYVzorFi5XpyvtUr9yJsHg3TJS65fIrWb3yimTe6Nu9d0zbnGq+4NWvRi2VPOynVg8UJ/CvaanM+9PFbWqihJbi,iv:WjYK9jil3R60U91vvlM+KrPpg0fiobRrIMV5zj8/NeU=,tag:PA2mxQE3g4CKJSz3vMTnCA==,type:comment]
#ENC[AES256_GCM,data:1jBQzktN4C8srzkJ9RmZCElPUW2QvGejxGLgMtl1oLs4/P9pATsVEC1Eo3dRGPQyuGQEhvu2tH28/pfUkf79kZxOOfYD,iv:251LXRB8lBB1VnXLRVNQv4JKt36NZSGpcQr1T9+2t90=,tag:Gi+3/nrFQ1suqCAomWEIQQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:7Vk=,iv:jW6mHbIY7UDjYnhC69AThO9e8p6n/86t4wwm3v/nAIE=,tag:1vgh5JDL6YthWGGBLTteeQ==,type:str]
kind: ENC[AES256_GCM,data:Fu6FbWic,iv:EAhwtSPeAui4XBDpyVqosIJUhanFYu6TazXqHS69l5E=,tag:LLiEdtUB5D4mIsFpp6N+hQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bz0h7kDWktvjq6HWilYKc2q+2WY=,iv:MEdxF6GRJM0ck3a/DKHkj42R2YvQrjWAHMyws6XRyZ4=,tag:ZdfdoGdiANw923DvsyyF3g==,type:str]
    namespace: ENC[AES256_GCM,data:YmBafDGiK4qJN80Ru9Rr,iv:yHefPTyczZ4+odwxeQrLF0E4Qmfi8Wbh/yp1nzkhTlA=,tag:5h20K3thBREwJra02yM0XA==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:QYwHtaiLyGqR,iv:MnQjsXXZmJWI/0mqxhKKmeoiq5C1fcpcv2XyB+rDQBA=,tag:/7ouzkyXLEDBlPajsDprEA==,type:str]
type: ENC[AES256_GCM,data:90oAweS0,iv:KJZGIuSGJ9YSZOgWLVExTr37qPV7SPzaV2ReVjKQbag=,tag:+yuumWtVV79cSrWyEOWrIw==,type:str]
data:
    password: ENC[AES256_GCM,data:VJIs+Y3TJE++m8/jk4JbPxzqqRwXjmAy,iv:ECPzcC8FlOMUhbHFrNl59nmnHQTWaStBa5frzkr/0OA=,tag:1exOPJ+Fp1plrVqjnIPDyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBalE5WGh2Mzd1d1FxY1dK
            SCtKTlg4YWg4V054UTN2MkdwR1UyRlp6L0RjCjVyYW1NY1lkR2hwNE44SDViSGc0
            KzlGOHo2c0N3Qk55WEpnM3E2NmtZZ00KLS0tIExaa1JkQjZTSlZPUEN6TWdLQy9U
            SFNkckx2MEFhU09ldHpJWDVHMk1KaWsKPEDS2+cfCuCRxzDLmqR7CGZgfgRSBnoc
            UwnZ+LfqThifFFCJjUzvt+A/LE+h9uJ3lkqAKFTuXVTrJbqDhYsGfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRGlqSytveVA5SWtFZzUx
            c2kzczU4U05sVlhhSlNkT2pzd0huQ08yeFg0CmFiTFZaUzBGczdwR0RFMG1VTUt2
            L3R0VW1UOGhoeFhrM29UNE1rSmpnRXcKLS0tIEJyNjk0RTBiOGplZFJRaExOR1dZ
            Qm56L2hzYWFxZzI4Slh3TlBVeGdJOWsKKVYxx+V0UfhYqpgFY6NwIpwJ0zW5j7rA
            TvcsKytX3hlVM9qzdTo8L9LTJGIx9ArQhfKjDbjGQFQ+lvxjaX3c9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVHU0UTZiaG1JMFBsWmZn
            YzdqWkdKUzVwVkVPYTl3STcycWlPeE9kNlRFClROclZEeWFRUVRiNHRoTkVHM251
            b0Nmejd2Yy9NemkvV0RrT3QvVFQrV2sKLS0tIHpXRkVnYWRCeWgwajhiaFpFVUFl
            ZnBtTVkrZWlZZGdRK0FRVXU2NnlUb0EKgUPQtfK+P3sDc+VdLRiSSNNfGo3gbxGd
            /xAUeRBT8glF3FTSU/AobyHUI71FxffgPrWQns1NSlt/GVx6cyfiEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
    lastmodified: "2026-06-04T09:29:10Z"
    mac: ENC[AES256_GCM,data:GzDgNULZBjs/fvej5yu1Mit9svtJcfFwxhMKKit9jW5zZK8iGDCrEKVXeElfOYKyCy5NW9W857NUgHrpr+U0IuOt5lFj/yKAKtAY/E777oQQKfLDKlPBPDT6qlROBaUXEw7tlZ7GnLPrEPVn4ioXjcnflt6JN0Y4rlR3QeVJIOk=,iv:e4L394arEvpKZo457f409vjBHKCwEWrfYTiPYnaaG+0=,tag:mySVF7Hb1VxNNmJY9Mf1Gg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:sKU=,iv:QZqJHrTAkgqpC42400pfoUe5+JezQUVw6cSa16thZh4=,tag:rwWYoIfZKgNffpihDTphwA==,type:str]
kind: ENC[AES256_GCM,data:rkZzeO64,iv:M9AZdrtabepwtj0fgWBa6TTcXeQVLeITP58BvwO+Ay8=,tag:dXUBNAd51DAdEpMxSYZqvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mv5n2BhoH3I2GAYR6ydpt07BPb9tVM+LOg==,iv:kZeWxC6KPbuVyw2mg34SppFyJ1bUtHd2nrBYUi86su8=,tag:L7Dp/PyOBxc46PLbQMxpYw==,type:str]
    namespace: ENC[AES256_GCM,data:px5tTJ/nylFvfN2BLj2o,iv:tpEukT7K64fg6eYAIXYkl6E0aN01mSrEbLxDIe7zAu0=,tag:Lsz3b5cMXVOgdTiLb0JkDA==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:UJK3hPwD3LMv,iv:eT09v5r6YCj7JFU4vP6BWQP9hKChaPDrCcJP9+W6O4s=,tag:Qr+XN7gC0KGchLgr9Aqc0Q==,type:str]
type: ENC[AES256_GCM,data:90h+9SkM,iv:I+dS8jL7tyo4saFeLb017OQcLVNfRwOWCGNJvNJvs8w=,tag:FSg41rUbSUM777u+RCRTGw==,type:str]
data:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:NVNckonhjbA7ZZ40yNMylpFuFj2TJDab/YrV+g==,iv:pfkilb2WZz9qJneaj70g/ui7dratZvYeU77xMiFgCu4=,tag:O0K6jyxJX0SuIpavQxAvWQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:DM+pYZuYcEhjqQ1sg441r8yhLQxsrdQKSnO9m2px1d8+H49tPCZ5y3SigexBATKKvE6QaQ==,iv:YHtfSYkUhMn/03wmx9FXfw+9IIYPCVtpKqGvdk+FF4M=,tag:cePn5lYBnGJYcnGDAt2YbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBalE5WGh2Mzd1d1FxY1dK
            SCtKTlg4YWg4V054UTN2MkdwR1UyRlp6L0RjCjVyYW1NY1lkR2hwNE44SDViSGc0
            KzlGOHo2c0N3Qk55WEpnM3E2NmtZZ00KLS0tIExaa1JkQjZTSlZPUEN6TWdLQy9U
            SFNkckx2MEFhU09ldHpJWDVHMk1KaWsKPEDS2+cfCuCRxzDLmqR7CGZgfgRSBnoc
            UwnZ+LfqThifFFCJjUzvt+A/LE+h9uJ3lkqAKFTuXVTrJbqDhYsGfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a58h6uzrz2pvk03swtjjzd7ekn9fxnyumxffr9ss4emkmgd03grq9v0eye
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRGlqSytveVA5SWtFZzUx
            c2kzczU4U05sVlhhSlNkT2pzd0huQ08yeFg0CmFiTFZaUzBGczdwR0RFMG1VTUt2
            L3R0VW1UOGhoeFhrM29UNE1rSmpnRXcKLS0tIEJyNjk0RTBiOGplZFJRaExOR1dZ
            Qm56L2hzYWFxZzI4Slh3TlBVeGdJOWsKKVYxx+V0UfhYqpgFY6NwIpwJ0zW5j7rA
            TvcsKytX3hlVM9qzdTo8L9LTJGIx9ArQhfKjDbjGQFQ+lvxjaX3c9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8v9n2z4y8kp8mfdytvxasud379n44dlrwkn88ynh5u2xnjt2aks8m0xz4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVHU0UTZiaG1JMFBsWmZn
            YzdqWkdKUzVwVkVPYTl3STcycWlPeE9kNlRFClROclZEeWFRUVRiNHRoTkVHM251
            b0Nmejd2Yy9NemkvV0RrT3QvVFQrV2sKLS0tIHpXRkVnYWRCeWgwajhiaFpFVUFl
            ZnBtTVkrZWlZZGdRK0FRVXU2NnlUb0EKgUPQtfK+P3sDc+VdLRiSSNNfGo3gbxGd
            /xAUeRBT8glF3FTSU/AobyHUI71FxffgPrWQns1NSlt/GVx6cyfiEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vexywt66s7fzakttu4tw0kyzyl6dc73u6jr870w08nsdegmanudshv3kjv
    lastmodified: "2026-06-04T09:29:10Z"
    mac: ENC[AES256_GCM,data:GzDgNULZBjs/fvej5yu1Mit9svtJcfFwxhMKKit9jW5zZK8iGDCrEKVXeElfOYKyCy5NW9W857NUgHrpr+U0IuOt5lFj/yKAKtAY/E777oQQKfLDKlPBPDT6qlROBaUXEw7tlZ7GnLPrEPVn4ioXjcnflt6JN0Y4rlR3QeVJIOk=,iv:e4L394arEvpKZo457f409vjBHKCwEWrfYTiPYnaaG+0=,tag:mySVF7Hb1VxNNmJY9Mf1Gg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
